const smartGlasses = [
  {
    id: 1,
    name: "Meta Ray-Ban Stories",
    brand: "Meta / Ray-Ban",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 299,
    releaseYear: 2024,
    image: "🕶️",
    summary: "Stylish AI-powered glasses with Meta AI assistant, livestreaming, and open-ear audio.",
    specs: {
      display: "No display",
      camera: "12 MP ultra-wide",
      video: "1080p @ 30fps",
      audio: "Open-ear speakers + 5-mic array",
      battery: "4 hours (moderate use)",
      charging: "USB-C charging case",
      weight: "49g",
      connectivity: "Bluetooth 5.3, Wi-Fi 6",
      assistant: "Meta AI (multimodal)",
      os: "Meta proprietary",
      storage: "32 GB",
      waterResistance: "IPX4 (splash proof)",
      lenses: "Prescription-compatible, transitions available",
      frameStyles: "Wayfarer, Headliner, multiple colors",
      features: ["Live translation", "AI visual questions", "Hands-free calls", "Music playback", "Livestream to Instagram/Facebook", "Shazam integration"],
    },
  },
  {
    id: 2,
    name: "Apple Vision Pro",
    brand: "Apple",
    category: "xr",
    categoryLabel: "XR / Mixed Reality",
    price: 3499,
    releaseYear: 2024,
    image: "🥽",
    summary: "Apple's spatial computing headset with ultra-high resolution passthrough and eye/hand tracking.",
    specs: {
      display: "Dual micro-OLED, 23M pixels total, 3,660 PPI",
      fov: "~100° horizontal",
      camera: "12 stereoscopic cameras + TrueDepth + LiDAR",
      video: "Spatial video capture (stereoscopic 3D)",
      audio: "Spatial Audio, dual-driver pods, 6-mic array",
      battery: "2 hours (external battery pack)",
      charging: "USB-C, external battery",
      weight: "600-650g",
      connectivity: "Wi-Fi 6E, Bluetooth 5.3",
      processor: "M2 + R1 chip",
      assistant: "Siri",
      os: "visionOS",
      storage: "256 GB / 512 GB / 1 TB",
      tracking: "Eye tracking, hand tracking, head tracking",
      controllers: "No controllers (eye + hand input)",
      waterResistance: "None",
      features: ["EyeSight (external display)", "Spatial Photos & Video", "Mac Virtual Display", "Persona (digital avatar)", "Optic ID (iris auth)", "Full App Store ecosystem"],
    },
  },
  {
    id: 3,
    name: "Meta Quest 3",
    brand: "Meta",
    category: "xr",
    categoryLabel: "XR / Mixed Reality",
    price: 499,
    releaseYear: 2023,
    image: "🥽",
    summary: "Affordable mixed reality headset with full-color passthrough and a large content library.",
    specs: {
      display: "Dual LCD, 2064×2208 per eye",
      fov: "110° horizontal, 96° vertical",
      camera: "Dual 4MP RGB passthrough + depth sensor",
      video: "Mixed reality recording",
      audio: "Integrated stereo, 3.5mm jack",
      battery: "2.2 hours average",
      charging: "USB-C",
      weight: "515g",
      connectivity: "Wi-Fi 6E, Bluetooth 5.3",
      processor: "Snapdragon XR2 Gen 2",
      assistant: "Meta AI",
      os: "Meta Horizon OS (Android-based)",
      storage: "128 GB / 512 GB",
      tracking: "Inside-out 6DoF, hand tracking v2.2",
      controllers: "Touch Plus controllers (included)",
      waterResistance: "None",
      features: ["Full-color passthrough MR", "Huge game library", "Xbox Cloud Gaming", "Fitness tracking", "Hand tracking", "Casting & streaming"],
    },
  },
  {
    id: 4,
    name: "Xreal Air 2 Ultra",
    brand: "Xreal",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 699,
    releaseYear: 2024,
    image: "👓",
    summary: "Lightweight AR glasses with 6DoF tracking, ideal for spatial computing and large virtual screens.",
    specs: {
      display: "Micro-OLED, 1920×1080 per eye",
      fov: "52° diagonal",
      camera: "Dual RGB + dual fisheye (6DoF SLAM)",
      video: "N/A (tethered device)",
      audio: "Open-ear directional speakers + mic",
      battery: "N/A (powered by connected device)",
      charging: "USB-C (passthrough power)",
      weight: "80g",
      connectivity: "USB-C (DP Alt Mode)",
      processor: "Relies on host device",
      assistant: "None built-in",
      os: "Nebula (companion app)",
      storage: "N/A",
      tracking: "6DoF SLAM tracking",
      controllers: "Phone / Beam Pro as controller",
      waterResistance: "None",
      lenses: "Prescription inserts available",
      features: ["6DoF spatial display", "330-inch equivalent virtual screen", "3DoF + 6DoF modes", "Low latency (<4ms)", "Works with phones/laptops/consoles", "Electrochromic dimming"],
    },
  },
  {
    id: 5,
    name: "Rokid Max 2",
    brand: "Rokid",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 380,
    releaseYear: 2024,
    image: "👓",
    summary: "Budget-friendly AR glasses with micro-LED display and large virtual screen for entertainment.",
    specs: {
      display: "Micro-LED, 1920×1080 per eye",
      fov: "50° diagonal",
      camera: "None",
      video: "N/A",
      audio: "Directional speakers + mic",
      battery: "N/A (tethered)",
      charging: "USB-C passthrough",
      weight: "75g",
      connectivity: "USB-C",
      processor: "Relies on host device",
      assistant: "None",
      os: "Companion app",
      storage: "N/A",
      tracking: "3DoF (head tracking)",
      controllers: "Phone / Rokid Station",
      waterResistance: "None",
      lenses: "Diopter adjustment built-in (-6.00)",
      features: ["300-inch virtual screen", "Micro-LED (high brightness)", "Diopter adjustment", "Lightweight", "Works with phones/Switch/Steam Deck", "Low latency display"],
    },
  },
  {
    id: 6,
    name: "Vuzix Ultralite Z100",
    brand: "Vuzix",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 599,
    releaseYear: 2025,
    image: "🕶️",
    summary: "Everyday smart glasses with a subtle green monochrome display and AI assistant integration.",
    specs: {
      display: "Monochrome green waveguide, 480×480",
      fov: "~15° diagonal",
      camera: "None",
      video: "N/A",
      audio: "Speaker + dual-mic",
      battery: "2 days standby, ~12 hrs active",
      charging: "Magnetic charging",
      weight: "38g",
      connectivity: "Bluetooth 5.3",
      processor: "Nordic nRF5340",
      assistant: "ChatGPT / custom via app",
      os: "Vuzix companion app (iOS/Android)",
      storage: "N/A",
      tracking: "Head nod/shake gestures",
      controllers: "Touch pad on temple",
      waterResistance: "IP67",
      lenses: "Prescription compatible",
      features: ["All-day battery", "Notification HUD", "Turn-by-turn navigation", "Teleprompter", "Fitness data overlay", "Extremely lightweight"],
    },
  },
  {
    id: 7,
    name: "Even Realities G1",
    brand: "Even Realities",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 499,
    releaseYear: 2025,
    image: "🕶️",
    summary: "Ultra-light AI glasses with a micro-LED display for text, navigation, and AI queries.",
    specs: {
      display: "Micro-LED waveguide, green monochrome",
      fov: "~15°",
      camera: "None",
      video: "N/A",
      audio: "Open-ear speakers + mic",
      battery: "~12 hours",
      charging: "Magnetic case",
      weight: "37g",
      connectivity: "Bluetooth 5.3",
      processor: "Proprietary SoC",
      assistant: "ChatGPT, DeepSeek (via app)",
      os: "Even companion app",
      storage: "N/A",
      tracking: "Touch gestures",
      controllers: "Temple touch controls + ring (optional)",
      waterResistance: "IPX4",
      lenses: "Prescription compatible",
      features: ["Real-time translation (13 languages)", "Teleprompter mode", "Navigation HUD", "Calendar & notifications", "Minimal design (looks like regular glasses)", "Dash ring controller"],
    },
  },
  {
    id: 8,
    name: "Brilliant Labs Frame",
    brand: "Brilliant Labs",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 349,
    releaseYear: 2024,
    image: "🕶️",
    summary: "Open-source AI glasses with multimodal AI, camera, and a tiny color OLED display.",
    specs: {
      display: "Micro-OLED, 640×400, color",
      fov: "~20° diagonal",
      camera: "8 MP",
      video: "Photo only",
      audio: "Mic only (no speaker)",
      battery: "~4 hours active",
      charging: "USB-C",
      weight: "39g",
      connectivity: "Bluetooth 5.3",
      processor: "Nordic nRF5340",
      assistant: "Noa (multimodal AI)",
      os: "Open-source (MicroPython / community apps)",
      storage: "N/A",
      tracking: "Tap gestures",
      controllers: "Tap interface",
      waterResistance: "None",
      lenses: "Prescription compatible",
      features: ["Open-source firmware", "Multimodal AI (Noa)", "Visual search & identify", "Real-time translation", "Color display", "Community app ecosystem"],
    },
  },
  {
    id: 9,
    name: "Google Android XR Glasses",
    brand: "Google / Samsung",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: null,
    priceNote: "TBA (Expected 2025)",
    releaseYear: 2025,
    comingSoon: true,
    image: "👓",
    summary: "Google's upcoming AR glasses running Android XR with Gemini AI integration.",
    specs: {
      display: "Full-color see-through AR (details TBA)",
      fov: "TBA",
      camera: "Camera with visual AI",
      video: "Expected",
      audio: "Spatial audio, microphones",
      battery: "TBA",
      charging: "TBA",
      weight: "TBA",
      connectivity: "Wi-Fi, Bluetooth, cellular (expected)",
      processor: "Qualcomm AR chipset (expected)",
      assistant: "Gemini AI (multimodal)",
      os: "Android XR",
      storage: "TBA",
      tracking: "6DoF (expected)",
      controllers: "Eye, hand, and voice",
      waterResistance: "TBA",
      features: ["Gemini AI built-in", "Full Android XR app ecosystem", "Google Maps AR navigation", "Translation overlay", "Circle to Search in AR", "Seamless phone integration"],
    },
  },
  {
    id: 10,
    name: "Snap Spectacles (2024)",
    brand: "Snap Inc.",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 99,
    priceNote: "$99/month subscription",
    releaseYear: 2024,
    image: "👓",
    summary: "Standalone AR glasses with Snap OS and Lens Studio, designed for developers.",
    specs: {
      display: "Dual waveguide, full color",
      fov: "46° diagonal",
      camera: "Dual cameras",
      video: "AR lens recording",
      audio: "Stereo speakers + dual mics",
      battery: "~45 minutes continuous AR",
      charging: "Charging case",
      weight: "226g",
      connectivity: "Wi-Fi 6, Bluetooth 5.2",
      processor: "Snapdragon AR1 Gen 1",
      assistant: "Snap AI",
      os: "Snap OS",
      storage: "TBA",
      tracking: "6DoF, hand tracking",
      controllers: "Hand tracking + touchpad",
      waterResistance: "None",
      features: ["Standalone AR (no phone)", "Lens Studio integration", "Spatial audio", "Hand tracking", "Location-based AR", "Developer-first platform"],
    },
  },
  {
    id: 11,
    name: "TCL RayNeo X2",
    brand: "TCL / RayNeo",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 699,
    releaseYear: 2024,
    image: "👓",
    summary: "Full-color AR glasses with Micro-LED display, standalone computing, and gesture control.",
    specs: {
      display: "Full-color Micro-LED waveguide",
      fov: "30° diagonal",
      camera: "8 MP (AF)",
      video: "1080p video",
      audio: "Dual speakers + 2-mic array",
      battery: "~3.5 hours",
      charging: "Magnetic charging",
      weight: "60g",
      connectivity: "Wi-Fi 5, Bluetooth 5.2",
      processor: "Qualcomm Snapdragon XR1",
      assistant: "AI assistant via app",
      os: "Android-based (RayNeo OS)",
      storage: "32 GB",
      tracking: "6DoF, gesture recognition",
      controllers: "Hand gestures + touch temple",
      waterResistance: "IPX4",
      lenses: "Prescription inserts",
      features: ["Standalone (no phone needed)", "Real-time AR navigation", "Translation (in-view text)", "Photo & video capture", "Gesture control", "Full-color display"],
    },
  },
  {
    id: 12,
    name: "Solos AirGo 3",
    brand: "Solos",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 249,
    releaseYear: 2024,
    image: "🕶️",
    summary: "Modular AI-powered audio glasses with GPT-4o integration and swappable front frames.",
    specs: {
      display: "None (audio-only base model)",
      fov: "N/A",
      camera: "Optional (with display module)",
      video: "N/A",
      audio: "Open-ear speakers + dual-mic",
      battery: "~10 hours music, ~6 hours calls",
      charging: "Magnetic charging",
      weight: "36g",
      connectivity: "Bluetooth 5.3",
      processor: "Qualcomm QCC5171",
      assistant: "SolosChat (GPT-4o powered)",
      os: "Solos app (iOS/Android)",
      storage: "N/A",
      tracking: "N/A",
      controllers: "Touch temple controls",
      waterResistance: "IPX4",
      lenses: "Prescription compatible, modular front frames",
      features: ["Modular design (swap frames)", "GPT-4o AI assistant", "Whisper mode (sub-vocal)", "All-day battery", "Fitness coaching", "Language translation (audio)"],
    },
  },
  {
    id: 13,
    name: "Lenovo ThinkReality A3",
    brand: "Lenovo",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 1499,
    releaseYear: 2023,
    image: "👓",
    summary: "Enterprise AR glasses with virtual multi-monitor workspace and 3D visualization.",
    specs: {
      display: "Dual 1080p micro-OLED, stereoscopic",
      fov: "45° diagonal",
      camera: "8 MP + dual fisheye",
      video: "N/A (enterprise)",
      audio: "Integrated speakers",
      battery: "N/A (tethered to PC or Motorola phone)",
      charging: "USB-C (host powered)",
      weight: "130g",
      connectivity: "USB-C tether",
      processor: "Qualcomm XR1",
      assistant: "None built-in",
      os: "Windows / Motorola Ready For",
      storage: "N/A (host device)",
      tracking: "6DoF head tracking",
      controllers: "Mouse/keyboard + head tracking",
      waterResistance: "None",
      lenses: "Prescription inserts",
      features: ["Virtual multi-monitor setup", "3D visualization", "Enterprise deployment tools", "PC tethered mode", "Motorola phone mode", "Collaboration features"],
    },
  },
  {
    id: 14,
    name: "Magic Leap 2",
    brand: "Magic Leap",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 3299,
    releaseYear: 2022,
    image: "👓",
    summary: "Enterprise AR headset with industry-leading optics, dimming, and medical/industrial applications.",
    specs: {
      display: "SRG waveguide, dynamic dimming",
      fov: "70° diagonal",
      camera: "12 MP RGB + depth",
      video: "Mixed reality capture",
      audio: "Integrated speakers + AUX",
      battery: "~3.5 hours",
      charging: "USB-C (compute pack)",
      weight: "260g (headset only)",
      connectivity: "Wi-Fi 6E, Bluetooth 5.0",
      processor: "AMD Zen 2 + GPGPU",
      assistant: "None (enterprise APIs)",
      os: "Magic Leap OS (AOSP-based)",
      storage: "256 GB",
      tracking: "Eye tracking, 6DoF, hand tracking",
      controllers: "Controller + hand tracking",
      waterResistance: "None",
      lenses: "Prescription inserts, global dimming",
      features: ["Dynamic dimming (outdoor use)", "Enterprise-grade security", "Medical visualization (FDA cleared)", "Hand & eye tracking", "Segmented dimming", "Large FoV for AR"],
    },
  },
  {
    id: 15,
    name: "INMO Air2",
    brand: "INMO",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 449,
    releaseYear: 2024,
    image: "🕶️",
    summary: "Lightweight standalone AI glasses with a color waveguide display and built-in ChatGPT.",
    specs: {
      display: "Color waveguide, 640×480",
      fov: "~17° diagonal",
      camera: "5 MP",
      video: "Photo + short video",
      audio: "Speaker + dual mic",
      battery: "~4 hours",
      charging: "Magnetic",
      weight: "27g (lightest in class)",
      connectivity: "Bluetooth 5.2, Wi-Fi",
      processor: "Qualcomm QCM2290",
      assistant: "ChatGPT integration",
      os: "INMO OS (Android-based)",
      storage: "32 GB",
      tracking: "Tap & gesture",
      controllers: "Temple touch",
      waterResistance: "IPX4",
      lenses: "Prescription compatible",
      features: ["Standalone (no phone needed)", "ChatGPT built-in", "Navigation HUD", "Real-time translation", "Notification display", "Ultra-lightweight (27g)"],
    },
  },
  {
    id: 16,
    name: "Meta Quest Pro",
    brand: "Meta",
    category: "xr",
    categoryLabel: "XR / Mixed Reality",
    price: 999,
    releaseYear: 2022,
    image: "🥽",
    summary: "Premium MR headset with face/eye tracking, color passthrough, and productivity features.",
    specs: {
      display: "Dual LCD, 1800×1920 per eye, local dimming",
      fov: "106° horizontal, 96° vertical",
      camera: "5 external cameras (color passthrough) + depth",
      video: "Mixed reality recording",
      audio: "Integrated spatial audio",
      battery: "1-2 hours",
      charging: "USB-C + charging dock",
      weight: "722g",
      connectivity: "Wi-Fi 6E, Bluetooth 5.2",
      processor: "Snapdragon XR2+ Gen 1",
      assistant: "Meta AI",
      os: "Meta Horizon OS",
      storage: "256 GB",
      tracking: "Eye tracking, face tracking, hand tracking, 6DoF",
      controllers: "Meta Quest Touch Pro (self-tracking)",
      waterResistance: "None",
      features: ["Eye + face tracking", "Self-tracking controllers", "Color passthrough MR", "Productivity workspace", "Slim pancake lenses", "Continuous peripheral display"],
    },
  },
  {
    id: 17,
    name: "Rayneo Air 2s",
    brand: "TCL / RayNeo",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 399,
    releaseYear: 2024,
    image: "👓",
    summary: "Entertainment-focused AR glasses with Sony micro-OLED and large virtual cinema display.",
    specs: {
      display: "Sony micro-OLED, 1920×1080 per eye",
      fov: "46° diagonal",
      camera: "None",
      video: "N/A",
      audio: "Dual speakers (Harman tuned)",
      battery: "N/A (tethered)",
      charging: "USB-C passthrough",
      weight: "76g",
      connectivity: "USB-C",
      processor: "Host device",
      assistant: "None",
      os: "Companion app",
      storage: "N/A",
      tracking: "3DoF",
      controllers: "Phone / remote",
      waterResistance: "None",
      lenses: "Diopter adjustment",
      features: ["201-inch virtual screen", "Sony micro-OLED", "Harman-tuned audio", "Electrochromic dimming", "3DoF head tracking", "Wide device compatibility"],
    },
  },
  {
    id: 18,
    name: "Samsung Project Moohan",
    brand: "Samsung / Google",
    category: "xr",
    categoryLabel: "XR / Mixed Reality",
    price: null,
    priceNote: "TBA (Expected 2025)",
    releaseYear: 2025,
    comingSoon: true,
    image: "🥽",
    summary: "Samsung's upcoming XR headset running Android XR with Gemini AI, co-developed with Google.",
    specs: {
      display: "Dual micro-OLED (Samsung-made), high resolution",
      fov: "TBA (expected ~110°)",
      camera: "Multi-camera passthrough + depth",
      video: "Spatial video (expected)",
      audio: "Spatial audio, multi-mic",
      battery: "TBA",
      charging: "USB-C",
      weight: "TBA",
      connectivity: "Wi-Fi 7, Bluetooth 5.4 (expected)",
      processor: "Qualcomm Snapdragon XR (latest gen)",
      assistant: "Gemini AI",
      os: "Android XR",
      storage: "TBA",
      tracking: "Eye, hand, head tracking (expected)",
      controllers: "Hand tracking + optional controller",
      waterResistance: "TBA",
      features: ["Android XR ecosystem", "Gemini AI multimodal", "Samsung display tech", "Google app ecosystem", "Multi-device integration", "Expected Galaxy ecosystem sync"],
    },
  },
  {
    id: 19,
    name: "Halliday Glasses",
    brand: "Halliday",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 399,
    releaseYear: 2025,
    image: "🕶️",
    summary: "AI glasses with a discreet DigiWindow display using light-guide flip prism technology.",
    specs: {
      display: "DigiWindow flip prism, color, ~320×240",
      fov: "~12° diagonal",
      camera: "None",
      video: "N/A",
      audio: "Open-ear speakers + mic",
      battery: "~8 hours",
      charging: "Magnetic",
      weight: "35g",
      connectivity: "Bluetooth 5.3",
      processor: "Nordic SoC",
      assistant: "ChatGPT / LLM integration",
      os: "Companion app (iOS/Android)",
      storage: "N/A",
      tracking: "Flip gesture (DigiWindow)",
      controllers: "Temple tap + flip gesture",
      waterResistance: "IPX4",
      lenses: "Prescription compatible",
      features: ["DigiWindow flip-down display", "Extremely discreet design", "Long battery life", "AI assistant (ChatGPT)", "Navigation prompts", "Notification display"],
    },
  },
  {
    id: 20,
    name: "Microsoft HoloLens 2",
    brand: "Microsoft",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 3500,
    releaseYear: 2019,
    image: "👓",
    summary: "Industry-standard enterprise AR headset with spatial mapping, hand tracking, and Azure integration.",
    specs: {
      display: "Waveguide, 2K resolution per eye",
      fov: "52° diagonal",
      camera: "8 MP stills + 1080p video, depth ToF",
      video: "1080p mixed reality capture",
      audio: "Spatial sound, 5-mic array",
      battery: "2-3 hours active",
      charging: "USB-C",
      weight: "566g",
      connectivity: "Wi-Fi 5, Bluetooth 5.0, USB-C",
      processor: "Qualcomm Snapdragon 850 + HPU 2.0",
      assistant: "Cortana / Dynamics 365 guides",
      os: "Windows Holographic",
      storage: "64 GB",
      tracking: "Eye tracking, hand tracking (articulated), head tracking, spatial mapping",
      controllers: "Hands-free (gesture + gaze + voice)",
      waterResistance: "None",
      lenses: "Flip-up visor, prescription inserts",
      features: ["Azure cloud integration", "Spatial anchors", "Remote Assist", "Dynamics 365 Guides", "Enterprise device management", "Research & military variants"],
    },
  },
];
