const smartGlasses = [
  {
    id: 1,
    name: "Meta Ray-Ban Stories",
    brand: "Meta / Ray-Ban",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 299,
    releaseYear: 2024,
    image: "🕶️",
    summary: "Stylish AI-powered glasses with Meta AI assistant, livestreaming, and open-ear audio.",
    specs: {
      display: "No display",
      camera: "12 MP ultra-wide",
      video: "1080p @ 30fps",
      audio: "Open-ear speakers + 5-mic array",
      battery: "4 hours (moderate use)",
      charging: "USB-C charging case",
      weight: "49g",
      connectivity: "Bluetooth 5.3, Wi-Fi 6",
      assistant: "Meta AI (multimodal)",
      os: "Meta proprietary",
      storage: "32 GB",
      waterResistance: "IPX4 (splash proof)",
      lenses: "Prescription-compatible, transitions available",
      frameStyles: "Wayfarer, Headliner, multiple colors",
      features: ["Live translation", "AI visual questions", "Hands-free calls", "Music playback", "Livestream to Instagram/Facebook", "Shazam integration"],
    },
  },
  {
    id: 2,
    name: "Apple Vision Pro",
    brand: "Apple",
    category: "xr",
    categoryLabel: "XR / Mixed Reality",
    price: 3499,
    releaseYear: 2024,
    image: "🥽",
    summary: "Apple's spatial computing headset with ultra-high resolution passthrough and eye/hand tracking.",
    specs: {
      display: "Dual micro-OLED, 23M pixels total, 3,660 PPI",
      fov: "~100° horizontal",
      camera: "12 stereoscopic cameras + TrueDepth + LiDAR",
      video: "Spatial video capture (stereoscopic 3D)",
      audio: "Spatial Audio, dual-driver pods, 6-mic array",
      battery: "2 hours (external battery pack)",
      charging: "USB-C, external battery",
      weight: "600-650g",
      connectivity: "Wi-Fi 6E, Bluetooth 5.3",
      processor: "M2 + R1 chip",
      assistant: "Siri",
      os: "visionOS",
      storage: "256 GB / 512 GB / 1 TB",
      tracking: "Eye tracking, hand tracking, head tracking",
      controllers: "No controllers (eye + hand input)",
      waterResistance: "None",
      features: ["EyeSight (external display)", "Spatial Photos & Video", "Mac Virtual Display", "Persona (digital avatar)", "Optic ID (iris auth)", "Full App Store ecosystem"],
    },
  },
  {
    id: 3,
    name: "Meta Quest 3",
    brand: "Meta",
    category: "xr",
    categoryLabel: "XR / Mixed Reality",
    price: 499,
    releaseYear: 2023,
    image: "🥽",
    summary: "Affordable mixed reality headset with full-color passthrough and a large content library.",
    specs: {
      display: "Dual LCD, 2064×2208 per eye",
      fov: "110° horizontal, 96° vertical",
      camera: "Dual 4MP RGB passthrough + depth sensor",
      video: "Mixed reality recording",
      audio: "Integrated stereo, 3.5mm jack",
      battery: "2.2 hours average",
      charging: "USB-C",
      weight: "515g",
      connectivity: "Wi-Fi 6E, Bluetooth 5.3",
      processor: "Snapdragon XR2 Gen 2",
      assistant: "Meta AI",
      os: "Meta Horizon OS (Android-based)",
      storage: "128 GB / 512 GB",
      tracking: "Inside-out 6DoF, hand tracking v2.2",
      controllers: "Touch Plus controllers (included)",
      waterResistance: "None",
      features: ["Full-color passthrough MR", "Huge game library", "Xbox Cloud Gaming", "Fitness tracking", "Hand tracking", "Casting & streaming"],
    },
  },
  {
    id: 4,
    name: "Xreal Air 2 Ultra",
    brand: "Xreal",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 699,
    releaseYear: 2024,
    image: "👓",
    summary: "Lightweight AR glasses with 6DoF tracking, ideal for spatial computing and large virtual screens.",
    specs: {
      display: "Micro-OLED, 1920×1080 per eye",
      fov: "52° diagonal",
      camera: "Dual RGB + dual fisheye (6DoF SLAM)",
      video: "N/A (tethered device)",
      audio: "Open-ear directional speakers + mic",
      battery: "N/A (powered by connected device)",
      charging: "USB-C (passthrough power)",
      weight: "80g",
      connectivity: "USB-C (DP Alt Mode)",
      processor: "Relies on host device",
      assistant: "None built-in",
      os: "Nebula (companion app)",
      storage: "N/A",
      tracking: "6DoF SLAM tracking",
      controllers: "Phone / Beam Pro as controller",
      waterResistance: "None",
      lenses: "Prescription inserts available",
      features: ["6DoF spatial display", "330-inch equivalent virtual screen", "3DoF + 6DoF modes", "Low latency (<4ms)", "Works with phones/laptops/consoles", "Electrochromic dimming"],
    },
  },
  {
    id: 5,
    name: "Rokid Max 2",
    brand: "Rokid",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 380,
    releaseYear: 2024,
    image: "👓",
    summary: "Budget-friendly AR glasses with micro-LED display and large virtual screen for entertainment.",
    specs: {
      display: "Micro-LED, 1920×1080 per eye",
      fov: "50° diagonal",
      camera: "None",
      video: "N/A",
      audio: "Directional speakers + mic",
      battery: "N/A (tethered)",
      charging: "USB-C passthrough",
      weight: "75g",
      connectivity: "USB-C",
      processor: "Relies on host device",
      assistant: "None",
      os: "Companion app",
      storage: "N/A",
      tracking: "3DoF (head tracking)",
      controllers: "Phone / Rokid Station",
      waterResistance: "None",
      lenses: "Diopter adjustment built-in (-6.00)",
      features: ["300-inch virtual screen", "Micro-LED (high brightness)", "Diopter adjustment", "Lightweight", "Works with phones/Switch/Steam Deck", "Low latency display"],
    },
  },
  {
    id: 6,
    name: "Vuzix Ultralite Z100",
    brand: "Vuzix",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 599,
    releaseYear: 2025,
    image: "🕶️",
    summary: "Everyday smart glasses with a subtle green monochrome display and AI assistant integration.",
    specs: {
      display: "Monochrome green waveguide, 480×480",
      fov: "~15° diagonal",
      camera: "None",
      video: "N/A",
      audio: "Speaker + dual-mic",
      battery: "2 days standby, ~12 hrs active",
      charging: "Magnetic charging",
      weight: "38g",
      connectivity: "Bluetooth 5.3",
      processor: "Nordic nRF5340",
      assistant: "ChatGPT / custom via app",
      os: "Vuzix companion app (iOS/Android)",
      storage: "N/A",
      tracking: "Head nod/shake gestures",
      controllers: "Touch pad on temple",
      waterResistance: "IP67",
      lenses: "Prescription compatible",
      features: ["All-day battery", "Notification HUD", "Turn-by-turn navigation", "Teleprompter", "Fitness data overlay", "Extremely lightweight"],
    },
  },
  {
    id: 7,
    name: "Even Realities G1",
    brand: "Even Realities",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 499,
    releaseYear: 2025,
    image: "🕶️",
    summary: "Ultra-light AI glasses with a micro-LED display for text, navigation, and AI queries.",
    specs: {
      display: "Micro-LED waveguide, green monochrome",
      fov: "~15°",
      camera: "None",
      video: "N/A",
      audio: "Open-ear speakers + mic",
      battery: "~12 hours",
      charging: "Magnetic case",
      weight: "37g",
      connectivity: "Bluetooth 5.3",
      processor: "Proprietary SoC",
      assistant: "ChatGPT, DeepSeek (via app)",
      os: "Even companion app",
      storage: "N/A",
      tracking: "Touch gestures",
      controllers: "Temple touch controls + ring (optional)",
      waterResistance: "IPX4",
      lenses: "Prescription compatible",
      features: ["Real-time translation (13 languages)", "Teleprompter mode", "Navigation HUD", "Calendar & notifications", "Minimal design (looks like regular glasses)", "Dash ring controller"],
    },
  },
  {
    id: 8,
    name: "Brilliant Labs Frame",
    brand: "Brilliant Labs",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 349,
    releaseYear: 2024,
    image: "🕶️",
    summary: "Open-source AI glasses with multimodal AI, camera, and a tiny color OLED display.",
    specs: {
      display: "Micro-OLED, 640×400, color",
      fov: "~20° diagonal",
      camera: "8 MP",
      video: "Photo only",
      audio: "Mic only (no speaker)",
      battery: "~4 hours active",
      charging: "USB-C",
      weight: "39g",
      connectivity: "Bluetooth 5.3",
      processor: "Nordic nRF5340",
      assistant: "Noa (multimodal AI)",
      os: "Open-source (MicroPython / community apps)",
      storage: "N/A",
      tracking: "Tap gestures",
      controllers: "Tap interface",
      waterResistance: "None",
      lenses: "Prescription compatible",
      features: ["Open-source firmware", "Multimodal AI (Noa)", "Visual search & identify", "Real-time translation", "Color display", "Community app ecosystem"],
    },
  },
  {
    id: 9,
    name: "Google Android XR Glasses",
    brand: "Google / Samsung",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: null,
    priceNote: "TBA (Expected 2025)",
    releaseYear: 2025,
    image: "👓",
    summary: "Google's upcoming AR glasses running Android XR with Gemini AI integration.",
    specs: {
      display: "Full-color see-through AR (details TBA)",
      fov: "TBA",
      camera: "Camera with visual AI",
      video: "Expected",
      audio: "Spatial audio, microphones",
      battery: "TBA",
      charging: "TBA",
      weight: "TBA",
      connectivity: "Wi-Fi, Bluetooth, cellular (expected)",
      processor: "Qualcomm AR chipset (expected)",
      assistant: "Gemini AI (multimodal)",
      os: "Android XR",
      storage: "TBA",
      tracking: "6DoF (expected)",
      controllers: "Eye, hand, and voice",
      waterResistance: "TBA",
      features: ["Gemini AI built-in", "Full Android XR app ecosystem", "Google Maps AR navigation", "Translation overlay", "Circle to Search in AR", "Seamless phone integration"],
    },
  },
  {
    id: 10,
    name: "Snap Spectacles (2024)",
    brand: "Snap Inc.",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 99,
    priceNote: "$99/month subscription",
    releaseYear: 2024,
    image: "👓",
    summary: "Standalone AR glasses with Snap OS and Lens Studio, designed for developers.",
    specs: {
      display: "Dual waveguide, full color",
      fov: "46° diagonal",
      camera: "Dual cameras",
      video: "AR lens recording",
      audio: "Stereo speakers + dual mics",
      battery: "~45 minutes continuous AR",
      charging: "Charging case",
      weight: "226g",
      connectivity: "Wi-Fi 6, Bluetooth 5.2",
      processor: "Snapdragon AR1 Gen 1",
      assistant: "Snap AI",
      os: "Snap OS",
      storage: "TBA",
      tracking: "6DoF, hand tracking",
      controllers: "Hand tracking + touchpad",
      waterResistance: "None",
      features: ["Standalone AR (no phone)", "Lens Studio integration", "Spatial audio", "Hand tracking", "Location-based AR", "Developer-first platform"],
    },
  },
  {
    id: 11,
    name: "TCL RayNeo X2",
    brand: "TCL / RayNeo",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 699,
    releaseYear: 2024,
    image: "👓",
    summary: "Full-color AR glasses with Micro-LED display, standalone computing, and gesture control.",
    specs: {
      display: "Full-color Micro-LED waveguide",
      fov: "30° diagonal",
      camera: "8 MP (AF)",
      video: "1080p video",
      audio: "Dual speakers + 2-mic array",
      battery: "~3.5 hours",
      charging: "Magnetic charging",
      weight: "60g",
      connectivity: "Wi-Fi 5, Bluetooth 5.2",
      processor: "Qualcomm Snapdragon XR1",
      assistant: "AI assistant via app",
      os: "Android-based (RayNeo OS)",
      storage: "32 GB",
      tracking: "6DoF, gesture recognition",
      controllers: "Hand gestures + touch temple",
      waterResistance: "IPX4",
      lenses: "Prescription inserts",
      features: ["Standalone (no phone needed)", "Real-time AR navigation", "Translation (in-view text)", "Photo & video capture", "Gesture control", "Full-color display"],
    },
  },
  {
    id: 12,
    name: "Solos AirGo 3",
    brand: "Solos",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 249,
    releaseYear: 2024,
    image: "🕶️",
    summary: "Modular AI-powered audio glasses with GPT-4o integration and swappable front frames.",
    specs: {
      display: "None (audio-only base model)",
      fov: "N/A",
      camera: "Optional (with display module)",
      video: "N/A",
      audio: "Open-ear speakers + dual-mic",
      battery: "~10 hours music, ~6 hours calls",
      charging: "Magnetic charging",
      weight: "36g",
      connectivity: "Bluetooth 5.3",
      processor: "Qualcomm QCC5171",
      assistant: "SolosChat (GPT-4o powered)",
      os: "Solos app (iOS/Android)",
      storage: "N/A",
      tracking: "N/A",
      controllers: "Touch temple controls",
      waterResistance: "IPX4",
      lenses: "Prescription compatible, modular front frames",
      features: ["Modular design (swap frames)", "GPT-4o AI assistant", "Whisper mode (sub-vocal)", "All-day battery", "Fitness coaching", "Language translation (audio)"],
    },
  },
  {
    id: 13,
    name: "Lenovo ThinkReality A3",
    brand: "Lenovo",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 1499,
    releaseYear: 2023,
    image: "👓",
    summary: "Enterprise AR glasses with virtual multi-monitor workspace and 3D visualization.",
    specs: {
      display: "Dual 1080p micro-OLED, stereoscopic",
      fov: "45° diagonal",
      camera: "8 MP + dual fisheye",
      video: "N/A (enterprise)",
      audio: "Integrated speakers",
      battery: "N/A (tethered to PC or Motorola phone)",
      charging: "USB-C (host powered)",
      weight: "130g",
      connectivity: "USB-C tether",
      processor: "Qualcomm XR1",
      assistant: "None built-in",
      os: "Windows / Motorola Ready For",
      storage: "N/A (host device)",
      tracking: "6DoF head tracking",
      controllers: "Mouse/keyboard + head tracking",
      waterResistance: "None",
      lenses: "Prescription inserts",
      features: ["Virtual multi-monitor setup", "3D visualization", "Enterprise deployment tools", "PC tethered mode", "Motorola phone mode", "Collaboration features"],
    },
  },
  {
    id: 14,
    name: "Magic Leap 2",
    brand: "Magic Leap",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 3299,
    releaseYear: 2022,
    image: "👓",
    summary: "Enterprise AR headset with industry-leading optics, dimming, and medical/industrial applications.",
    specs: {
      display: "SRG waveguide, dynamic dimming",
      fov: "70° diagonal",
      camera: "12 MP RGB + depth",
      video: "Mixed reality capture",
      audio: "Integrated speakers + AUX",
      battery: "~3.5 hours",
      charging: "USB-C (compute pack)",
      weight: "260g (headset only)",
      connectivity: "Wi-Fi 6E, Bluetooth 5.0",
      processor: "AMD Zen 2 + GPGPU",
      assistant: "None (enterprise APIs)",
      os: "Magic Leap OS (AOSP-based)",
      storage: "256 GB",
      tracking: "Eye tracking, 6DoF, hand tracking",
      controllers: "Controller + hand tracking",
      waterResistance: "None",
      lenses: "Prescription inserts, global dimming",
      features: ["Dynamic dimming (outdoor use)", "Enterprise-grade security", "Medical visualization (FDA cleared)", "Hand & eye tracking", "Segmented dimming", "Large FoV for AR"],
    },
  },
  {
    id: 15,
    name: "INMO Air2",
    brand: "INMO",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 449,
    releaseYear: 2024,
    image: "🕶️",
    summary: "Lightweight standalone AI glasses with a color waveguide display and built-in ChatGPT.",
    specs: {
      display: "Color waveguide, 640×480",
      fov: "~17° diagonal",
      camera: "5 MP",
      video: "Photo + short video",
      audio: "Speaker + dual mic",
      battery: "~4 hours",
      charging: "Magnetic",
      weight: "27g (lightest in class)",
      connectivity: "Bluetooth 5.2, Wi-Fi",
      processor: "Qualcomm QCM2290",
      assistant: "ChatGPT integration",
      os: "INMO OS (Android-based)",
      storage: "32 GB",
      tracking: "Tap & gesture",
      controllers: "Temple touch",
      waterResistance: "IPX4",
      lenses: "Prescription compatible",
      features: ["Standalone (no phone needed)", "ChatGPT built-in", "Navigation HUD", "Real-time translation", "Notification display", "Ultra-lightweight (27g)"],
    },
  },
  {
    id: 16,
    name: "Meta Quest Pro",
    brand: "Meta",
    category: "xr",
    categoryLabel: "XR / Mixed Reality",
    price: 999,
    releaseYear: 2022,
    image: "🥽",
    summary: "Premium MR headset with face/eye tracking, color passthrough, and productivity features.",
    specs: {
      display: "Dual LCD, 1800×1920 per eye, local dimming",
      fov: "106° horizontal, 96° vertical",
      camera: "5 external cameras (color passthrough) + depth",
      video: "Mixed reality recording",
      audio: "Integrated spatial audio",
      battery: "1-2 hours",
      charging: "USB-C + charging dock",
      weight: "722g",
      connectivity: "Wi-Fi 6E, Bluetooth 5.2",
      processor: "Snapdragon XR2+ Gen 1",
      assistant: "Meta AI",
      os: "Meta Horizon OS",
      storage: "256 GB",
      tracking: "Eye tracking, face tracking, hand tracking, 6DoF",
      controllers: "Meta Quest Touch Pro (self-tracking)",
      waterResistance: "None",
      features: ["Eye + face tracking", "Self-tracking controllers", "Color passthrough MR", "Productivity workspace", "Slim pancake lenses", "Continuous peripheral display"],
    },
  },
  {
    id: 17,
    name: "Rayneo Air 2s",
    brand: "TCL / RayNeo",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 399,
    releaseYear: 2024,
    image: "👓",
    summary: "Entertainment-focused AR glasses with Sony micro-OLED and large virtual cinema display.",
    specs: {
      display: "Sony micro-OLED, 1920×1080 per eye",
      fov: "46° diagonal",
      camera: "None",
      video: "N/A",
      audio: "Dual speakers (Harman tuned)",
      battery: "N/A (tethered)",
      charging: "USB-C passthrough",
      weight: "76g",
      connectivity: "USB-C",
      processor: "Host device",
      assistant: "None",
      os: "Companion app",
      storage: "N/A",
      tracking: "3DoF",
      controllers: "Phone / remote",
      waterResistance: "None",
      lenses: "Diopter adjustment",
      features: ["201-inch virtual screen", "Sony micro-OLED", "Harman-tuned audio", "Electrochromic dimming", "3DoF head tracking", "Wide device compatibility"],
    },
  },
  {
    id: 18,
    name: "Samsung Project Moohan",
    brand: "Samsung / Google",
    category: "xr",
    categoryLabel: "XR / Mixed Reality",
    price: null,
    priceNote: "TBA (Expected 2025)",
    releaseYear: 2025,
    image: "🥽",
    summary: "Samsung's upcoming XR headset running Android XR with Gemini AI, co-developed with Google.",
    specs: {
      display: "Dual micro-OLED (Samsung-made), high resolution",
      fov: "TBA (expected ~110°)",
      camera: "Multi-camera passthrough + depth",
      video: "Spatial video (expected)",
      audio: "Spatial audio, multi-mic",
      battery: "TBA",
      charging: "USB-C",
      weight: "TBA",
      connectivity: "Wi-Fi 7, Bluetooth 5.4 (expected)",
      processor: "Qualcomm Snapdragon XR (latest gen)",
      assistant: "Gemini AI",
      os: "Android XR",
      storage: "TBA",
      tracking: "Eye, hand, head tracking (expected)",
      controllers: "Hand tracking + optional controller",
      waterResistance: "TBA",
      features: ["Android XR ecosystem", "Gemini AI multimodal", "Samsung display tech", "Google app ecosystem", "Multi-device integration", "Expected Galaxy ecosystem sync"],
    },
  },
  {
    id: 19,
    name: "Halliday Glasses",
    brand: "Halliday",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 399,
    releaseYear: 2025,
    image: "🕶️",
    summary: "AI glasses with a discreet DigiWindow display using light-guide flip prism technology.",
    specs: {
      display: "DigiWindow flip prism, color, ~320×240",
      fov: "~12° diagonal",
      camera: "None",
      video: "N/A",
      audio: "Open-ear speakers + mic",
      battery: "~8 hours",
      charging: "Magnetic",
      weight: "35g",
      connectivity: "Bluetooth 5.3",
      processor: "Nordic SoC",
      assistant: "ChatGPT / LLM integration",
      os: "Companion app (iOS/Android)",
      storage: "N/A",
      tracking: "Flip gesture (DigiWindow)",
      controllers: "Temple tap + flip gesture",
      waterResistance: "IPX4",
      lenses: "Prescription compatible",
      features: ["DigiWindow flip-down display", "Extremely discreet design", "Long battery life", "AI assistant (ChatGPT)", "Navigation prompts", "Notification display"],
    },
  },
  {
    id: 20,
    name: "Microsoft HoloLens 2",
    brand: "Microsoft",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 3500,
    releaseYear: 2019,
    image: "👓",
    summary: "Industry-standard enterprise AR headset with spatial mapping, hand tracking, and Azure integration.",
    specs: {
      display: "Waveguide, 2K resolution per eye",
      fov: "52° diagonal",
      camera: "8 MP stills + 1080p video, depth ToF",
      video: "1080p mixed reality capture",
      audio: "Spatial sound, 5-mic array",
      battery: "2-3 hours active",
      charging: "USB-C",
      weight: "566g",
      connectivity: "Wi-Fi 5, Bluetooth 5.0, USB-C",
      processor: "Qualcomm Snapdragon 850 + HPU 2.0",
      assistant: "Cortana / Dynamics 365 guides",
      os: "Windows Holographic",
      storage: "64 GB",
      tracking: "Eye tracking, hand tracking (articulated), head tracking, spatial mapping",
      controllers: "Hands-free (gesture + gaze + voice)",
      waterResistance: "None",
      lenses: "Flip-up visor, prescription inserts",
      features: ["Azure cloud integration", "Spatial anchors", "Remote Assist", "Dynamics 365 Guides", "Enterprise device management", "Research & military variants"],
    },
  },
  {
    id: 21,
    name: "Xreal Air",
    brand: "Xreal",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 379,
    releaseYear: 2022,
    image: "👓",
    summary: "Lightweight tethered AR glasses with Sony Micro-OLED display and 201-inch virtual screen.",
    specs: {
      display: "Sony Micro-OLED, 1920×1080 per eye",
      fov: "46° diagonal",
      camera: "None",
      video: "N/A (tethered display)",
      audio: "Open-ear directional speakers + dual mic",
      battery: "N/A (powered by host device)",
      charging: "USB-C passthrough",
      weight: "79g",
      connectivity: "USB-C (DP Alt Mode)",
      processor: "Relies on host device",
      assistant: "None built-in",
      os: "Nebula companion app",
      storage: "N/A",
      tracking: "3DoF head tracking",
      controllers: "Phone / Beam adapter",
      waterResistance: "None",
      lenses: "Prescription inserts available",
      features: ["201-inch virtual screen at 6m", "130-inch at 4m equivalent", "46° FOV Birdbath optics", "Micro-OLED 400 nits brightness", "Compatible with Android/PC/Mac", "Low latency display"],
    },
  },
  {
    id: 22,
    name: "Xreal Air 2",
    brand: "Xreal",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 399,
    releaseYear: 2023,
    image: "👓",
    summary: "Improved AR glasses over the original Air with brighter Sony Micro-OLED and 120 Hz refresh rate.",
    specs: {
      display: "Sony Micro-OLED, 1920×1080 per eye",
      fov: "46° diagonal",
      camera: "None",
      video: "N/A (tethered display)",
      audio: "Open-ear speakers + dual mic",
      battery: "N/A (powered by host device)",
      charging: "USB-C passthrough",
      weight: "72g",
      connectivity: "USB-C (DP Alt Mode)",
      processor: "Relies on host device",
      assistant: "None built-in",
      os: "Nebula companion app",
      storage: "N/A",
      tracking: "3DoF head tracking",
      controllers: "Phone / Beam adapter",
      waterResistance: "None",
      lenses: "Prescription inserts available",
      features: ["120 Hz refresh rate", "25% higher peak brightness than Air", "72g lightweight design", "Improved color calibration", "Works with phones/laptops/consoles", "130-inch virtual screen at 4m"],
    },
  },
  {
    id: 23,
    name: "Xreal Air 2 Pro",
    brand: "Xreal",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 449,
    releaseYear: 2023,
    image: "👓",
    summary: "Premium version of Xreal Air 2 with electrochromic dimming lenses for adjustable light control.",
    specs: {
      display: "Sony Micro-OLED, 1920×1080 per eye",
      fov: "46° diagonal",
      camera: "None",
      video: "N/A (tethered display)",
      audio: "Open-ear speakers + dual mic",
      battery: "N/A (powered by host device)",
      charging: "USB-C passthrough",
      weight: "75g",
      connectivity: "USB-C (DP Alt Mode)",
      processor: "Relies on host device",
      assistant: "None built-in",
      os: "Nebula companion app",
      storage: "N/A",
      tracking: "3DoF head tracking",
      controllers: "Phone / Beam Pro as controller",
      waterResistance: "None",
      lenses: "Electrochromic dimming, prescription inserts available",
      features: ["Electrochromic lens dimming", "3 tint levels (clear to dark)", "120 Hz refresh rate", "Sony Micro-OLED display", "Outdoor usability", "Compatible with phones/laptops/consoles"],
    },
  },
  {
    id: 24,
    name: "Xreal One",
    brand: "Xreal",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 499,
    releaseYear: 2024,
    image: "👓",
    summary: "First AR glasses with Xreal's custom X1 spatial computing chip for ultra-low latency 3DoF display.",
    specs: {
      display: "Micro-OLED, 1920×1080 per eye",
      fov: "50° diagonal",
      camera: "None",
      video: "N/A (tethered display)",
      audio: "Open-ear speakers (Bose-tuned) + mic",
      battery: "N/A (powered by host device)",
      charging: "USB-C passthrough",
      weight: "84g",
      connectivity: "USB-C (DP Alt Mode)",
      processor: "X1 independent spatial computing chip",
      assistant: "None built-in",
      os: "Nebula companion app",
      storage: "N/A",
      tracking: "3DoF (X1 chip, ~3ms latency)",
      controllers: "Phone / Beam adapter",
      waterResistance: "None",
      lenses: "Prescription inserts available",
      features: ["X1 chip — world's first in AR glasses", "~3ms motion-to-photon latency", "171-inch virtual screen at 4m", "Bose-tuned directional audio", "Native spatial stability", "700 nits peak brightness"],
    },
  },
  {
    id: 25,
    name: "Xreal One Pro",
    brand: "Xreal",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 599,
    releaseYear: 2025,
    image: "👓",
    summary: "Top-tier Xreal AR glasses with X-Prism optics, 57° FOV, X1 chip, and 6DoF upgrade support.",
    specs: {
      display: "Micro-OLED, 1920×1080 per eye, X-Prism optics",
      fov: "57° diagonal",
      camera: "None",
      video: "N/A (tethered display)",
      audio: "Open-ear speakers (Bose-tuned) + mic",
      battery: "N/A (powered by host device)",
      charging: "USB-C passthrough",
      weight: "84g",
      connectivity: "USB-C (DP Alt Mode)",
      processor: "X1 independent spatial computing chip",
      assistant: "None built-in",
      os: "Nebula companion app",
      storage: "N/A",
      tracking: "3DoF native; 6DoF via Ultra Computing Kit add-on",
      controllers: "Phone / Beam adapter",
      waterResistance: "None",
      lenses: "X-Prism flat-prism, prescription inserts available",
      features: ["X-Prism optics (40% smaller lens)", "57° FOV — widest in tethered AR class", "X1 chip ~3ms latency", "171-inch virtual screen", "Optional 6DoF with Ultra Kit", "Adjustable IPD (57-66mm)"],
    },
  },
  {
    id: 26,
    name: "Rokid Max",
    brand: "Rokid",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 499,
    releaseYear: 2023,
    image: "👓",
    summary: "Popular tethered AR glasses with Micro-OLED display, 50° FOV, and built-in diopter adjustment.",
    specs: {
      display: "Micro-OLED, 1920×1080 per eye",
      fov: "50° diagonal",
      camera: "None",
      video: "N/A (tethered display)",
      audio: "Directional speakers + mic",
      battery: "N/A (tethered)",
      charging: "USB-C passthrough",
      weight: "75g",
      connectivity: "USB-C",
      processor: "Relies on host device",
      assistant: "None",
      os: "Companion app / Rokid Station",
      storage: "N/A",
      tracking: "3DoF head tracking",
      controllers: "Phone / Rokid Station",
      waterResistance: "None",
      lenses: "Built-in diopter adjustment (0 to -6.00)",
      features: ["215-inch virtual cinema screen", "600 nits peak brightness", "120 Hz refresh rate", "Built-in myopia correction", "HDCP streaming support", "Works with Switch/Steam Deck/PS5"],
    },
  },
  {
    id: 27,
    name: "Rokid AR Lite",
    brand: "Rokid",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 749,
    releaseYear: 2024,
    image: "👓",
    summary: "Standalone AR system pairing Rokid Max 2 glasses with Snapdragon 6 Gen 1 compute puck.",
    specs: {
      display: "Micro-OLED, 1920×1080 per eye",
      fov: "50° diagonal",
      camera: "None on glasses",
      video: "N/A",
      audio: "Directional speakers + mic",
      battery: "5000 mAh (Station 2 compute puck)",
      charging: "18W fast charge (USB-C)",
      weight: "75g glasses + 178g Station 2",
      connectivity: "Wi-Fi 6, Bluetooth 5.2",
      processor: "Qualcomm Snapdragon 6 Gen 1 (Station 2)",
      assistant: "AI via YodaOS-Master",
      os: "YodaOS-Master (Android-based)",
      storage: "128 GB",
      tracking: "3DoF",
      controllers: "Station 2 puck (touchpad + buttons)",
      waterResistance: "None",
      lenses: "Built-in diopter adjustment",
      features: ["First Snapdragon 6 Gen 1 AR device", "Multi-app windowed mode", "Standalone (no phone needed)", "5000 mAh battery in puck", "Spatial computing YodaOS", "600 nits Micro-OLED display"],
    },
  },
  {
    id: 28,
    name: "Rokid AR Joy",
    brand: "Rokid",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 499,
    releaseYear: 2023,
    image: "👓",
    summary: "Standalone AR bundle combining Rokid Max glasses with the Rokid Station Android TV compute puck.",
    specs: {
      display: "Micro-OLED, 1920×1080 per eye",
      fov: "50° diagonal",
      camera: "None",
      video: "N/A",
      audio: "Directional speakers + mic",
      battery: "~3 hours (Station battery)",
      charging: "USB-C",
      weight: "75g glasses + Station puck",
      connectivity: "Wi-Fi 5, Bluetooth",
      processor: "Rokid Station (Android TV)",
      assistant: "Voice assistant via app",
      os: "YodaOS-C (Android TV-based)",
      storage: "32 GB",
      tracking: "3DoF",
      controllers: "Station remote / touch interface",
      waterResistance: "None",
      lenses: "Built-in diopter adjustment",
      features: ["Portable standalone AR setup", "Google Play certified (Station)", "Streaming apps (Netflix, YouTube)", "Compact carry case included", "Works as tethered glasses too", "Cloud gaming compatible"],
    },
  },
  {
    id: 29,
    name: "Vuzix Blade 2",
    brand: "Vuzix",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 1299,
    releaseYear: 2022,
    image: "👓",
    summary: "Enterprise AR smart glasses with full-color waveguide display, HD camera, and Android 11.",
    specs: {
      display: "Full-color waveguide, 480×480",
      fov: "~20° diagonal",
      camera: "8 MP HD camera",
      video: "1080p video recording",
      audio: "Stereo speakers + noise-cancelling mic",
      battery: "~8 hours active",
      charging: "USB-C",
      weight: "~95g",
      connectivity: "Wi-Fi 5 (2.4/5 GHz), Bluetooth 5.0",
      processor: "Qualcomm QCS4020",
      assistant: "Alexa built-in",
      os: "Android 11",
      storage: "40 GB",
      tracking: "3DoF head tracking",
      controllers: "Touch pad on temple + voice",
      waterResistance: "ANSI Z87.1 certified",
      lenses: "Safety glass rated (ANSI Z87.1)",
      features: ["Full-color waveguide AR display", "Android 11 enterprise apps", "Alexa voice assistant", "40 GB internal storage", "Safety-rated lens (ANSI Z87.1)", "MDM integration ready"],
    },
  },
  {
    id: 30,
    name: "Vuzix Shield",
    brand: "Vuzix",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 1999,
    releaseYear: 2024,
    image: "👓",
    summary: "Stylish enterprise AR glasses with uLED stereo display, autofocus HD camera, and titanium frame.",
    specs: {
      display: "Dual uLED waveguide, full-color",
      fov: "30° diagonal",
      camera: "Autofocus HD camera",
      video: "HD see-what-I-see streaming",
      audio: "Integrated speakers + noise-cancelling mic",
      battery: "All-day use (~8+ hours)",
      charging: "USB-C",
      weight: "~100g",
      connectivity: "Wi-Fi 6, Bluetooth 5.2",
      processor: "Qualcomm octa-core",
      assistant: "Voice assistant compatible",
      os: "Android (Vuzix enterprise)",
      storage: "TBA",
      tracking: "Head tracking",
      controllers: "Touch temple + voice",
      waterResistance: "ANSI Z87.1, splash-resistant",
      lenses: "3D-printed titanium frame, prescription-ready",
      features: ["World's first miniature uLED stereo display", "92% RGB color accuracy", "ANSI Z87.1 safety certification", "Titanium 3D-printed frame", "Autofocus HD streaming camera", "Enterprise-grade security"],
    },
  },
  {
    id: 31,
    name: "Ray-Ban Meta (Wayfarer)",
    brand: "Meta / Ray-Ban",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 299,
    releaseYear: 2023,
    image: "🕶️",
    summary: "Second-gen Ray-Ban Meta in classic Wayfarer frame with 12 MP camera, Meta AI, and live streaming.",
    specs: {
      display: "No display",
      camera: "12 MP ultra-wide",
      video: "1080p @ 30fps (up to 3K photo)",
      audio: "Open-ear speakers + 5-mic array",
      battery: "~6 hours mixed use (30 hrs with case)",
      charging: "USB-C charging case",
      weight: "48g",
      connectivity: "Bluetooth 5.3, Wi-Fi 6",
      processor: "Qualcomm Snapdragon AR1 Gen 1",
      assistant: "Meta AI (multimodal)",
      os: "Meta proprietary",
      storage: "32 GB",
      waterResistance: "IPX4",
      lenses: "Prescription-compatible, tinted options",
      features: ["12 MP ultra-wide camera", "Meta AI multimodal queries", "Live streaming to Instagram/Facebook", "Shazam music recognition", "Real-time translation (Live AI)", "Wayfarer iconic frame style"],
    },
  },
  {
    id: 32,
    name: "Amazon Echo Frames (3rd Gen)",
    brand: "Amazon",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 269,
    releaseYear: 2023,
    image: "🕶️",
    summary: "Alexa-powered audio smart glasses with open-ear sound, multi-point Bluetooth, and all-day comfort.",
    specs: {
      display: "None",
      camera: "None",
      video: "N/A",
      audio: "Open-ear speakers + dual mic",
      battery: "~14 hours (moderate use)",
      charging: "USB-C",
      weight: "~31g",
      connectivity: "Bluetooth 5.1 (multi-point, 2 devices)",
      processor: "Custom Amazon SoC",
      assistant: "Amazon Alexa",
      os: "Alexa companion app (iOS/Android)",
      storage: "N/A",
      tracking: "N/A",
      controllers: "Temple button controls",
      waterResistance: "IPX4",
      lenses: "Prescription-compatible, blue light filtering, sunglass options",
      features: ["Alexa always-on assistant", "Multi-point Bluetooth pairing", "7 frame styles (incl. Carrera collab)", "40% more audio vs Gen 2", "IPX4 water resistance", "Prescription-ready lenses"],
    },
  },
  {
    id: 33,
    name: "Huawei Eyewear 2",
    brand: "Huawei",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 300,
    releaseYear: 2023,
    image: "🕶️",
    summary: "Premium audio smart glasses with 11-hour battery, Zeiss lenses, and IP54 water resistance.",
    specs: {
      display: "None",
      camera: "None",
      video: "N/A",
      audio: "Open-ear speakers + dual mic (wind-resistant)",
      battery: "11 hours continuous",
      charging: "Magnetic pogo-pin",
      weight: "~33g (titanium variant)",
      connectivity: "Bluetooth 5.2",
      processor: "Embedded audio SoC",
      assistant: "Huawei AI (HarmonyOS linked)",
      os: "AI Life app (Huawei)",
      storage: "N/A",
      tracking: "N/A",
      controllers: "Touch temple gestures",
      waterResistance: "IP54",
      lenses: "Zeiss prescription lenses available, multiple frame styles",
      features: ["Zeiss prescription lens partnership", "11-hour battery (30% larger than Eyewear 1)", "IP54 water resistance", "Wind-noise-resistant dual mic", "Titanium frame edition", "HarmonyOS device integration"],
    },
  },
  {
    id: 34,
    name: "Xiaomi Smart Glasses",
    brand: "Xiaomi",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 370,
    releaseYear: 2022,
    image: "👓",
    summary: "China-exclusive standalone AR glasses with dual cameras, Micro-OLED display, and Android.",
    specs: {
      display: "Sony Micro-OLED, monochrome, 3000 nits",
      fov: "~12° monocular",
      camera: "50 MP primary + 8 MP periscope",
      video: "HD video recording",
      audio: "Integrated speakers + mic",
      battery: "~3-4 hours",
      charging: "USB-C",
      weight: "~51g",
      connectivity: "Wi-Fi (dual-band), Bluetooth 5.0",
      processor: "Qualcomm Snapdragon 8-core",
      assistant: "Xiao AI voice assistant",
      os: "Android (MIUI-based)",
      storage: "32 GB (3 GB RAM)",
      tracking: "None (monocular HUD)",
      controllers: "Touch temple + voice",
      waterResistance: "None",
      lenses: "Monocular waveguide prism",
      features: ["50 MP primary camera", "3000 nits Micro-OLED display", "Standalone Android device", "Navigation HUD", "Translation & notifications", "China market only"],
    },
  },
  {
    id: 35,
    name: "Xiaomi AI Glasses",
    brand: "Xiaomi",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 275,
    releaseYear: 2025,
    image: "🕶️",
    summary: "Lightweight AI glasses with 12 MP 2K camera, XiaoAI assistant, and 8.6-hour battery.",
    specs: {
      display: "None",
      camera: "12 MP ultra-wide, 2K @ 30fps",
      video: "2K video with EIS stabilization",
      audio: "Open-ear speakers + 5-mic array",
      battery: "~8.6 hours",
      charging: "45-minute full charge",
      weight: "40g",
      connectivity: "Bluetooth, Wi-Fi",
      processor: "Qualcomm AR1 Gen 1",
      assistant: "XiaoAI (Xiaomi AI assistant)",
      os: "Xiaomi companion app",
      storage: "N/A (streams to phone)",
      tracking: "N/A",
      controllers: "Temple button + voice",
      waterResistance: "IPX4",
      lenses: "Multiple frame styles, prescription-compatible",
      features: ["12 MP 2K camera", "8.6-hour battery (2x Ray-Ban Meta)", "XiaoAI multimodal AI", "Object recognition & translation", "QR code scan via camera", "Available in 3 color styles"],
    },
  },
  {
    id: 36,
    name: "Oppo Air Glass 2",
    brand: "Oppo",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: null,
    priceNote: "China only / No global pricing",
    releaseYear: 2023,
    image: "👓",
    summary: "Ultra-light monocular AR glasses with MicroLED display, Snapdragon 4100, and 3-hour battery.",
    specs: {
      display: "MicroLED monocular waveguide, 1000 nits",
      fov: "~12° monocular",
      camera: "None",
      video: "N/A",
      audio: "Integrated speakers + mic",
      battery: "~3 hours (200 mAh)",
      charging: "Magnetic pin",
      weight: "38g",
      connectivity: "Bluetooth (smartphone companion)",
      processor: "Qualcomm Snapdragon 4100",
      assistant: "AndesGPT via Oppo phone",
      os: "ColorOS companion",
      storage: "N/A",
      tracking: "N/A",
      controllers: "Touch temple + voice",
      waterResistance: "None stated",
      lenses: "Monocular prism",
      features: ["38g ultra-light design", "1000 nits MicroLED display", "Real-time navigation overlay", "Call & notification display", "Language translation", "Voice-to-text transcription"],
    },
  },
  {
    id: 37,
    name: "Viture One XR",
    brand: "Viture",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 479,
    releaseYear: 2023,
    image: "👓",
    summary: "Kickstarter-funded XR glasses with electrochromic film, Harman audio, and wide device compatibility.",
    specs: {
      display: "Micro-OLED, 1920×1080 per eye",
      fov: "38.4° diagonal",
      camera: "None",
      video: "N/A (tethered display)",
      audio: "Harman-designed open-ear speakers + mic",
      battery: "N/A (tethered)",
      charging: "USB-C passthrough",
      weight: "78g",
      connectivity: "USB-C (DP Alt Mode)",
      processor: "Relies on host device",
      assistant: "None built-in",
      os: "SpaceWalker companion app",
      storage: "N/A",
      tracking: "3DoF head tracking",
      controllers: "Phone / SpaceWalker Neckband accessory",
      waterResistance: "None",
      lenses: "Electrochromic dimming, diopter adjustment (0 to -5.00)",
      features: ["Electrochromic lens dimming", "Harman-tuned spatial audio", "Raised $2.6M on Kickstarter", "120-inch virtual screen", "iPhone & Android compatible", "SpaceWalker MoVR neckband accessory"],
    },
  },
  {
    id: 38,
    name: "Viture Pro XR",
    brand: "Viture",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 459,
    releaseYear: 2024,
    image: "👓",
    summary: "Premium XR glasses with 4000-nit display, 120 Hz, electrochromic film, and Harman audio.",
    specs: {
      display: "Dual Micro-OLED, 1920×1080 per eye",
      fov: "~38° diagonal",
      camera: "None",
      video: "N/A (tethered display)",
      audio: "Harman-designed open-ear speakers + mic",
      battery: "N/A (tethered)",
      charging: "USB-C passthrough",
      weight: "77g",
      connectivity: "USB-C (DP Alt Mode)",
      processor: "Relies on host device",
      assistant: "None built-in",
      os: "SpaceWalker companion app",
      storage: "N/A",
      tracking: "3DoF head tracking",
      controllers: "Phone / SpaceWalker Neckband",
      waterResistance: "None",
      lenses: "Electrochromic film (99.9% light block), diopter adjustment",
      features: ["4000 nits peak brightness", "Electrochromic blocks 99.9% external light", "120 Hz refresh rate", "Harman spatial audio", "135-inch virtual screen", "Real-time 2D-to-3D conversion"],
    },
  },
  {
    id: 39,
    name: "Razer Anzu",
    brand: "Razer",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 199,
    releaseYear: 2021,
    image: "🕶️",
    summary: "Gaming-brand audio smart glasses with Bluetooth 5.1, 5-hour battery, and blue light filtering lenses.",
    specs: {
      display: "None",
      camera: "None",
      video: "N/A",
      audio: "Open-ear speakers + omnidirectional mic",
      battery: "~5 hours",
      charging: "Proprietary USB-A magnetic",
      weight: "48g",
      connectivity: "Bluetooth 5.1 (60ms low latency)",
      processor: "Embedded BT SoC",
      assistant: "Google/Siri via phone",
      os: "Razer app (iOS/Android)",
      storage: "N/A",
      tracking: "N/A",
      controllers: "Touch temple",
      waterResistance: "IPX4",
      lenses: "35% blue light filter or polarized sunglass (swappable)",
      features: ["Swappable blue-light / sunglass lenses", "60ms low-latency Bluetooth 5.1", "Razer gaming brand design", "Compact omnidirectional mic", "Two frame styles (round/rectangle)", "Google Assistant & Siri compatible"],
    },
  },
  {
    id: 40,
    name: "Bose Frames Tempo",
    brand: "Bose",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 249,
    releaseYear: 2021,
    image: "🕶️",
    summary: "Sport-focused Bose audio sunglasses with open-ear sound, 8-hour battery, and polarized lenses.",
    specs: {
      display: "None",
      camera: "None",
      video: "N/A",
      audio: "Bose OpenAudio dual speakers + mic",
      battery: "~8 hours",
      charging: "USB-C",
      weight: "~45g",
      connectivity: "Bluetooth 5.1 (30 ft / 9m range)",
      processor: "Embedded BT audio SoC",
      assistant: "Google/Siri via phone",
      os: "Bose Connect app",
      storage: "N/A",
      tracking: "Integrated motion sensor",
      controllers: "Capacitive touch temple",
      waterResistance: "IPX4",
      lenses: "Polarized 99% UV protection, scratch & shatter resistant (65mm width)",
      features: ["Bose OpenAudio system (wide sound)", "8-hour battery life", "Loud enough at 40 km/h wind speed", "Capacitive touch volume control", "Sport/athletic design", "Motion sensor auto-off when upside-down"],
    },
  },
  {
    id: 41,
    name: "Fauna Audio Glasses",
    brand: "Fauna",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 299,
    releaseYear: 2022,
    image: "🕶️",
    summary: "Scandinavian-designed audio smart glasses with premium Zeiss lenses and 4-hour streaming battery.",
    specs: {
      display: "None",
      camera: "None",
      video: "N/A",
      audio: "4 MEMS speakers + dual mic per frame",
      battery: "~4 hours streaming (20 hours standby)",
      charging: "Proprietary magnetic USB",
      weight: "50g",
      connectivity: "Bluetooth 5.0",
      processor: "USound Danube UAM-P audio module",
      assistant: "Google/Siri via phone",
      os: "Fauna companion app",
      storage: "N/A",
      tracking: "N/A",
      controllers: "Dual touchpad temples",
      waterResistance: "IP52",
      lenses: "Zeiss optical lenses, prescription-compatible",
      features: ["Zeiss lens partnership", "4-speaker MEMS audio system", "Scandinavian fashion design", "4 frame styles available", "IP52 dust & splash resistant", "Prescription fitting by optician"],
    },
  },
  {
    id: 42,
    name: "Nreal Light",
    brand: "Nreal (now Xreal)",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 599,
    releaseYear: 2021,
    image: "👓",
    summary: "One of the first consumer AR glasses, phone-tethered with 52° FOV and 6DoF spatial tracking.",
    specs: {
      display: "Waveguide, 1920×1080 per eye",
      fov: "52° diagonal",
      camera: "Dual RGB cameras (6DoF SLAM)",
      video: "Mixed reality capture",
      audio: "Spatial speakers (arm-mounted) + mic",
      battery: "N/A (tethered to Android phone)",
      charging: "USB-C from phone",
      weight: "106g",
      connectivity: "USB-C tether to compatible Android",
      processor: "Relies on host Android phone",
      assistant: "None built-in",
      os: "Nebula (early version)",
      storage: "N/A",
      tracking: "6DoF SLAM",
      controllers: "Phone touchpad as controller",
      waterResistance: "None",
      lenses: "Waveguide optics",
      features: ["52° wide FOV for the era", "6DoF spatial tracking", "Mixed reality experiences", "First consumer AR with spatial tracking", "Carrier-sold (Verizon US)", "Developer SDK available"],
    },
  },
  {
    id: 43,
    name: "Epson Moverio BT-45C",
    brand: "Epson",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: null,
    priceNote: "Enterprise pricing (contact Epson)",
    releaseYear: 2022,
    image: "👓",
    summary: "Enterprise AR glasses with binocular Full HD Si-OLED, 34° FOV, flip-up visor, and USB-C tether.",
    specs: {
      display: "Binocular Si-OLED, Full HD 1080p per eye",
      fov: "34° diagonal",
      camera: "8 MP center camera + flip-up design",
      video: "1080p video recording",
      audio: "Integrated speakers + mic",
      battery: "N/A (tethered to host device)",
      charging: "USB-C host powered",
      weight: "~180g",
      connectivity: "USB-C tether (Android/Windows host)",
      processor: "Relies on host device",
      assistant: "None built-in",
      os: "Android / Windows (host device)",
      storage: "N/A (host device)",
      tracking: "3DoF head tracking",
      controllers: "Host device",
      waterResistance: "Splash-resistant (rubber bumpers)",
      lenses: "Flip-up visor, 500,000:1 contrast ratio",
      features: ["Flip-up visor removes AR when needed", "Helmet-compatible mounting", "Binocular Full HD Si-OLED", "High-contrast display (500,000:1)", "Industrial frontline worker focus", "8 MP camera for see-what-I-see"],
    },
  },
  {
    id: 44,
    name: "Lenovo Glasses T1",
    brand: "Lenovo",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 499,
    releaseYear: 2023,
    image: "👓",
    summary: "Wearable private display glasses with Micro-OLED, 60 Hz, and USB-C connection for phones and laptops.",
    specs: {
      display: "Micro-OLED, 1920×1080 per eye",
      fov: "~45° (equivalent ~100-inch screen)",
      camera: "None",
      video: "N/A (display-only device)",
      audio: "Side-mounted frame speakers",
      battery: "N/A (USB-C powered)",
      charging: "USB-C passthrough",
      weight: "~80g",
      connectivity: "USB-C (DP Alt Mode)",
      processor: "Relies on host device",
      assistant: "None built-in",
      os: "Compatible with Windows/Android/iOS",
      storage: "N/A",
      tracking: "Gyroscope (image lock)",
      controllers: "Brightness / volume buttons on frame",
      waterResistance: "None",
      lenses: "Swappable nose clips, prescription frame attachment",
      features: ["Micro-OLED 10,000:1 contrast", "Image lock mode (gyroscope)", "USB-C universal compatibility", "Private viewing mode", "Prescription lens adapter", "Multiple nose clip sizes"],
    },
  },
  {
    id: 45,
    name: "Varjo XR-4",
    brand: "Varjo",
    category: "xr",
    categoryLabel: "XR / Mixed Reality",
    price: 3990,
    releaseYear: 2023,
    image: "🥽",
    summary: "Enterprise XR headset with 4K per-eye display, 20 MP passthrough cameras, and 120° FOV.",
    specs: {
      display: "Dual OLED+LCD hybrid, 3840×3744 per eye",
      fov: "120° horizontal, 105° vertical",
      camera: "Dual 20 MP RGB passthrough + depth LiDAR",
      video: "Photorealistic mixed reality capture",
      audio: "Spatial 3D audio, noise-cancelling mic",
      battery: "Tethered to PC (no battery)",
      charging: "PC-tethered via cable",
      weight: "~800g (with cable)",
      connectivity: "USB-C + DisplayPort tether, Wi-Fi 6E (optional)",
      processor: "Tethered to host PC (no on-board GPU)",
      assistant: "None built-in",
      os: "Varjo Base software (Windows)",
      storage: "N/A (PC-dependent)",
      tracking: "Inside-out 6DoF + optional SteamVR base stations",
      controllers: "Varjo controllers + hand tracking",
      waterResistance: "None",
      features: ["51 PPD — near human-eye clarity", "Dual 20 MP passthrough cameras", "SteamVR / OpenVR compatible", "Focal Edition with eye-tracked autofocus", "Military & aviation training certified", "96% DCI-P3 color accuracy"],
    },
  },
  {
    id: 46,
    name: "HTC Vive XR Elite",
    brand: "HTC",
    category: "xr",
    categoryLabel: "XR / Mixed Reality",
    price: 1099,
    releaseYear: 2023,
    image: "🥽",
    summary: "Compact standalone MR/VR headset with detachable battery, 110° FOV, and PC streaming support.",
    specs: {
      display: "Dual LCD, 1920×1920 per eye",
      fov: "110° diagonal",
      camera: "4 color cameras (passthrough) + depth",
      video: "Mixed reality recording",
      audio: "Integrated speakers + 3.5mm jack",
      battery: "~2 hours standalone (hot-swappable)",
      charging: "USB-C",
      weight: "625g (with battery) / 273g (without)",
      connectivity: "Wi-Fi 6E, Bluetooth 5.2",
      processor: "Qualcomm Snapdragon XR2 Gen 1",
      assistant: "None built-in",
      os: "VIVE OS (Android-based)",
      storage: "128 GB (12 GB RAM)",
      tracking: "6DoF inside-out, hand tracking",
      controllers: "VIVE Wrist Trackers + Touch controllers",
      waterResistance: "None",
      features: ["Hot-swappable battery", "Detach battery for ultra-light use", "PCVR streaming via USB-C/Wi-Fi", "SteamVR compatible", "Compact pancake lens design", "Eye tracking (optional add-on)"],
    },
  },
  {
    id: 47,
    name: "PlayStation VR2",
    brand: "Sony",
    category: "xr",
    categoryLabel: "XR / Mixed Reality",
    price: 549,
    releaseYear: 2023,
    image: "🥽",
    summary: "PS5-exclusive VR headset with OLED displays, eye tracking, haptic feedback, and 4K resolution.",
    specs: {
      display: "Dual OLED, 2000×2040 per eye (HDR)",
      fov: "110° diagonal",
      camera: "4 external cameras + IR eye tracking",
      video: "Cinematic mode (PS5 screen on virtual 2D)",
      audio: "Built-in mic, 3.5mm headphone jack, 3D audio",
      battery: "~3-4 hours (tethered to PS5)",
      charging: "USB-C (tethered to PS5)",
      weight: "560g",
      connectivity: "USB-C tether to PS5",
      processor: "Powered by PS5",
      assistant: "None",
      os: "PS5 system software",
      storage: "N/A (PS5 storage)",
      tracking: "Inside-out 6DoF, eye tracking",
      controllers: "PS VR2 Sense controllers (adaptive triggers + haptics)",
      waterResistance: "None",
      features: ["Eye tracking + foveated rendering", "Adaptive trigger haptics (Sense controllers)", "Headset rumble feedback", "4K HDR OLED displays", "PS5 exclusive game library", "Single USB-C cable setup"],
    },
  },
  {
    id: 48,
    name: "Pimax Crystal",
    brand: "Pimax",
    category: "xr",
    categoryLabel: "XR / Mixed Reality",
    price: 1599,
    releaseYear: 2023,
    image: "🥽",
    summary: "High-resolution hybrid standalone/PCVR headset with 2880×2880 QLED per eye and 140° FOV.",
    specs: {
      display: "QLED, 2880×2880 per eye",
      fov: "Up to 140° diagonal (wide lens)",
      camera: "Passthrough cameras (B&W)",
      video: "N/A (gaming/simulation focus)",
      audio: "Integrated spatial audio + 3.5mm",
      battery: "~2 hours standalone",
      charging: "USB-C",
      weight: "~860g (with halo strap)",
      connectivity: "Wi-Fi 6E, USB-C, DisplayPort",
      processor: "Qualcomm XR2 Gen 1 (standalone) + PCVR mode",
      assistant: "None built-in",
      os: "PiOS (standalone) / SteamVR (PCVR)",
      storage: "256 GB (8 GB RAM)",
      tracking: "Inside-out 6DoF + optional SteamVR lighthouse",
      controllers: "Pimax sword controllers included",
      waterResistance: "None",
      lenses: "Interchangeable (wide/standard aspheric glass)",
      features: ["35 PPD high-clarity display", "Hybrid standalone + PCVR modes", "Interchangeable optical lenses", "Eye tracking built-in", "Motorized auto-IPD adjustment", "SteamVR base station optional tracking"],
    },
  },
  {
    id: 49,
    name: "Bigscreen Beyond",
    brand: "Bigscreen VR",
    category: "xr",
    categoryLabel: "XR / Mixed Reality",
    price: 999,
    releaseYear: 2023,
    image: "🥽",
    summary: "World's smallest SteamVR headset with custom-fit micro-OLED panels and 127g ultra-light design.",
    specs: {
      display: "Dual micro-OLED, 2560×2560 per eye",
      fov: "93° horizontal, 90° vertical",
      camera: "None (no passthrough)",
      video: "N/A",
      audio: "3.5mm jack (no built-in speakers)",
      battery: "N/A (PC-tethered)",
      charging: "PC-tethered",
      weight: "127g",
      connectivity: "USB-C + DisplayPort tether",
      processor: "Tethered to host PC",
      assistant: "None",
      os: "SteamVR (Windows)",
      storage: "N/A",
      tracking: "SteamVR outside-in (base stations required)",
      controllers: "SteamVR-compatible (not included)",
      waterResistance: "None",
      lenses: "Custom-fit pancake optics (IPD measured at order)",
      features: ["World's smallest/lightest PCVR headset", "127g total weight", "Custom IPD fit per order", "2560×2560 per eye micro-OLED", "28 PPD clarity", "SteamVR ecosystem access"],
    },
  },
  {
    id: 50,
    name: "Pico 4 Ultra",
    brand: "Pico (ByteDance)",
    category: "xr",
    categoryLabel: "XR / Mixed Reality",
    price: 599,
    releaseYear: 2024,
    image: "🥽",
    summary: "ByteDance's flagship MR headset with 32 MP passthrough cameras, Snapdragon XR2 Gen 2, and Wi-Fi 7.",
    specs: {
      display: "Dual LCD, 2160×2160 per eye",
      fov: "104° diagonal",
      camera: "Dual 32 MP RGB + iToF depth sensor",
      video: "Spatial video capture",
      audio: "Integrated spatial audio + mic",
      battery: "~2.5 hours",
      charging: "45W fast charge USB-C",
      weight: "580g total (304g front + 276g rear cushion)",
      connectivity: "Wi-Fi 7, Bluetooth 5.3",
      processor: "Qualcomm Snapdragon XR2 Gen 2",
      assistant: "None built-in",
      os: "PICO OS (Android-based)",
      storage: "256 GB (12 GB RAM)",
      tracking: "Inside-out 6DoF, eye tracking, hand tracking",
      controllers: "PICO 4 Ultra controllers (included)",
      waterResistance: "None",
      features: ["32 MP high-fidelity passthrough cameras", "Snapdragon XR2 Gen 2 (same as Quest 3)", "Wi-Fi 7 connectivity", "45W fast charging", "Spatial video recording", "Eye tracking & hand tracking"],
    },
  },
  {
    id: 51,
    name: "Nubia Neovision Glass",
    brand: "Nubia / ZTE",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 529,
    releaseYear: 2023,
    image: "👓",
    summary: "ZTE's AR glasses with Micro-OLED 3500 PPI display, 43° FOV, and 120-inch virtual screen.",
    specs: {
      display: "Micro-OLED, 1080p binocular, 3500 PPI",
      fov: "43° diagonal",
      camera: "None",
      video: "N/A (tethered display)",
      audio: "Dual speakers + mic",
      battery: "N/A (tethered)",
      charging: "USB-C passthrough",
      weight: "79g",
      connectivity: "USB-C (DP Alt Mode)",
      processor: "Relies on host device",
      assistant: "None built-in",
      os: "Nubia companion app",
      storage: "N/A",
      tracking: "3DoF",
      controllers: "Phone / console",
      waterResistance: "None",
      lenses: "Myopia adjustment (0 to -500°)",
      features: ["3500 PPI Micro-OLED — ultra-sharp", "1800 nits peak brightness", "120-inch virtual screen", "43° FOV with myopia adjustment", "Works with phones/laptops/consoles/drones", "Unveiled at MWC 2023"],
    },
  },
  {
    id: 52,
    name: "Meizu StarV Air 2",
    brand: "Meizu",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 489,
    releaseYear: 2024,
    image: "👓",
    summary: "Ultra-light 44g AR glasses with MicroLED display, real-time AI translation, and AR navigation.",
    specs: {
      display: "MicroLED, 2000 nits",
      fov: "30° diagonal",
      camera: "None",
      video: "N/A",
      audio: "Open-ear speakers + mic",
      battery: "N/A (tethered)",
      charging: "USB-C passthrough",
      weight: "44g",
      connectivity: "USB-C",
      processor: "Relies on host device",
      assistant: "AI translation via Flyme XR",
      os: "Flyme XR 2.0 (Meizu)",
      storage: "N/A",
      tracking: "3DoF",
      controllers: "Phone / touch temple",
      waterResistance: "None",
      lenses: "Step-less electric IPD adjustment",
      features: ["44g ultra-light frame", "2000 nits MicroLED display", "Real-time AI translation (13 languages)", "AR turn-by-turn navigation", "Electric IPD adjustment", "Flyme XR spatial OS"],
    },
  },
  {
    id: 53,
    name: "Tecno Pocket Vision",
    brand: "Tecno",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 349,
    releaseYear: 2024,
    image: "👓",
    summary: "Gaming-focused AR glasses with 0.71-inch Micro-OLED, 215-inch virtual screen, and diopter support.",
    specs: {
      display: "Micro-OLED, 2K resolution (0.71-inch panel)",
      fov: "~40° (equivalent 215-inch at 20 ft)",
      camera: "None",
      video: "Supports 4K input, 60 Hz",
      audio: "Integrated speakers + mic",
      battery: "N/A (powered by Pocket Go handheld)",
      charging: "USB-C from host",
      weight: "~80g",
      connectivity: "USB-C",
      processor: "Relies on Tecno Pocket Go (Ryzen 7 8840HS)",
      assistant: "None built-in",
      os: "Windows 11 (via Pocket Go)",
      storage: "N/A (host device)",
      tracking: "6-axis gyroscope with AI enhancement",
      controllers: "Pocket Go handheld controls",
      waterResistance: "None",
      lenses: "Adjustable diopter",
      features: ["215-inch virtual screen", "Windows 11 gaming PC in glasses", "Paired with Pocket Go handheld", "6-axis AI-enhanced gyroscope", "4K input support", "Diopter adjustment for glasses wearers"],
    },
  },
  {
    id: 54,
    name: "ThirdEye Gen X2",
    brand: "ThirdEye Gen",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 2999,
    releaseYear: 2022,
    image: "👓",
    summary: "Enterprise mixed reality glasses with 42° FOV, 13 MP camera, and all-in-one Android platform.",
    specs: {
      display: "Waveguide, 1280×720 per eye",
      fov: "42° diagonal",
      camera: "13 MP with dual noise-cancelling mic",
      video: "HD see-what-I-see video streaming",
      audio: "Integrated speakers + dual noise-cancelling mic",
      battery: "1750 mAh",
      charging: "USB-C",
      weight: "~312g",
      connectivity: "Wi-Fi (dual-band), Bluetooth, GPS",
      processor: "4-core CPU, 4 GB RAM",
      assistant: "Voice-activated",
      os: "Android 8.1",
      storage: "64 GB",
      tracking: "SLAM-based, voice + gesture",
      controllers: "Voice + gesture (hands-free)",
      waterResistance: "None",
      features: ["All-in-one standalone AR", "42° FOV waveguide display", "Remote collaboration platform", "VisionEye SDK (Unity/Android Studio)", "GPS built-in", "Targeted at industrial frontline workers"],
    },
  },
  {
    id: 55,
    name: "RayNeo Air 2",
    brand: "TCL / RayNeo",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 379,
    releaseYear: 2023,
    image: "👓",
    summary: "Budget-friendly AR display glasses with Sony Micro-OLED, 120 Hz, and wide device compatibility.",
    specs: {
      display: "Sony Micro-OLED, 1920×1080 per eye",
      fov: "46° diagonal",
      camera: "None",
      video: "N/A (tethered display)",
      audio: "Whisper Mode 2.0 dual speakers + mic",
      battery: "N/A (tethered)",
      charging: "USB-C passthrough",
      weight: "76g",
      connectivity: "USB-C (DP Alt Mode)",
      processor: "Relies on host device",
      assistant: "None built-in",
      os: "RayNeo companion app",
      storage: "N/A",
      tracking: "3DoF",
      controllers: "Phone / TCL Neckband",
      waterResistance: "None",
      lenses: "9-level nose bridge adjustments",
      features: ["Sony Micro-OLED 600 nits", "120 Hz refresh rate", "201-inch virtual cinema", "Whisper Mode 2.0 noise cancellation", "Works with Switch/Steam Deck/PS5", "9-position fit adjustment"],
    },
  },
  {
    id: 56,
    name: "Rokid Air",
    brand: "Rokid",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 299,
    releaseYear: 2022,
    image: "👓",
    summary: "Lightweight standalone AR glasses with 43° FOV, built-in battery, diopter correction, and Android.",
    specs: {
      display: "OLED, 1920×1080 per eye",
      fov: "43° diagonal",
      camera: "None",
      video: "N/A",
      audio: "Directional speakers + mic",
      battery: "~5 hours (5000 mAh)",
      charging: "USB-C",
      weight: "83g",
      connectivity: "USB-C, Bluetooth",
      processor: "Qualcomm (embedded)",
      assistant: "AI via companion",
      os: "YodaOS (Android-based)",
      storage: "32 GB (2 GB RAM)",
      tracking: "3DoF",
      controllers: "Touch on temple + phone",
      waterResistance: "None",
      lenses: "Diopter adjustment (0 to -5.00)",
      features: ["Built-in 5000 mAh battery", "Standalone Android device", "5-hour battery life", "43° FOV Birdbath optics", "Diopter correction", "Voice AI assistant"],
    },
  },
  {
    id: 57,
    name: "Campfire One",
    brand: "Campfire",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 599,
    releaseYear: 2024,
    image: "👓",
    summary: "Kickstarter-funded AR collaboration glasses for 3D design review and remote teamwork.",
    specs: {
      display: "Micro-OLED, stereoscopic 3D",
      fov: "50° diagonal",
      camera: "Tracking cameras",
      video: "N/A",
      audio: "Integrated speakers + mic",
      battery: "N/A (tethered to Campfire Console)",
      charging: "USB-C (host powered)",
      weight: "85g",
      connectivity: "USB-C tether",
      processor: "Host device (Campfire Console)",
      assistant: "None",
      os: "Campfire OS",
      storage: "N/A (host)",
      tracking: "6DoF head + hand tracking",
      controllers: "Campfire Console + hand gestures",
      waterResistance: "None",
      features: ["3D model collaboration", "Multi-user AR sessions", "CAD file review", "Stereoscopic 3D display", "6DoF spatial tracking", "Enterprise collaboration tools"],
    },
  },
  {
    id: 58,
    name: "Norm Glasses",
    brand: "Norm",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 299,
    releaseYear: 2024,
    image: "🕶️",
    summary: "Kickstarter-backed smart glasses with HD camera, open-ear audio, and AI assistant integration.",
    specs: {
      display: "No display",
      camera: "12 MP wide-angle",
      video: "1080p @ 30fps",
      audio: "Open-ear speakers + dual mic",
      battery: "~5 hours",
      charging: "USB-C charging case",
      weight: "42g",
      connectivity: "Bluetooth 5.3, Wi-Fi",
      processor: "Qualcomm QCC5171",
      assistant: "ChatGPT / custom AI via app",
      os: "Norm companion app (iOS/Android)",
      storage: "32 GB onboard",
      tracking: "N/A",
      controllers: "Temple touch controls",
      waterResistance: "IPX4",
      lenses: "Prescription compatible, multiple styles",
      features: ["HD photo & video capture", "AI assistant integration", "Open-ear spatial audio", "Hands-free calls", "Lightweight normal appearance", "Live translation"],
    },
  },
  {
    id: 59,
    name: "Vuzix Z100 Lite",
    brand: "Vuzix",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 299,
    releaseYear: 2025,
    image: "🕶️",
    summary: "Budget version of Vuzix Ultralite with notification display and extended battery life.",
    specs: {
      display: "Monochrome green waveguide",
      fov: "~12° diagonal",
      camera: "None",
      video: "N/A",
      audio: "Speaker + mic",
      battery: "~2 days standby",
      charging: "Magnetic charging",
      weight: "36g",
      connectivity: "Bluetooth 5.3",
      processor: "Nordic nRF5340",
      assistant: "Via companion app",
      os: "Vuzix companion app",
      storage: "N/A",
      tracking: "Head gestures",
      controllers: "Temple touch",
      waterResistance: "IP65",
      lenses: "Prescription compatible",
      features: ["Notification HUD", "Ultra-lightweight", "Multi-day battery", "Turn-by-turn navigation", "Fitness tracking overlay", "Discreet design"],
    },
  },
  {
    id: 60,
    name: "Lucyd Lyte",
    brand: "Lucyd",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 149,
    releaseYear: 2023,
    image: "🕶️",
    summary: "Affordable Bluetooth audio smart glasses with ChatGPT integration and multiple frame styles.",
    specs: {
      display: "No display",
      camera: "None",
      video: "N/A",
      audio: "Open-ear speakers + dual mic",
      battery: "~6 hours music, ~4 hours calls",
      charging: "USB-C",
      weight: "45g",
      connectivity: "Bluetooth 5.1",
      processor: "Qualcomm audio SoC",
      assistant: "ChatGPT (via Lucyd app)",
      os: "Lucyd app (iOS/Android)",
      storage: "N/A",
      tracking: "N/A",
      controllers: "Temple touch",
      waterResistance: "IPX4",
      lenses: "Prescription compatible, 14+ frame styles",
      features: ["ChatGPT voice assistant", "Open-ear audio", "14+ frame styles", "Hands-free calling", "Music playback", "Affordable price point"],
    },
  },
  {
    id: 61,
    name: "Envision Glasses",
    brand: "Envision",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 2499,
    releaseYear: 2023,
    image: "🕶️",
    summary: "AI-powered smart glasses designed for blind and visually impaired users with scene description.",
    specs: {
      display: "No display (audio-based)",
      camera: "8 MP (Google Glass Enterprise frame)",
      video: "N/A",
      audio: "Bone conduction speaker + mic",
      battery: "~6 hours",
      charging: "USB-C",
      weight: "46g",
      connectivity: "Bluetooth 5.0, Wi-Fi",
      processor: "Qualcomm Snapdragon",
      assistant: "Envision AI (GPT-4 powered)",
      os: "Envision OS (Android-based)",
      storage: "32 GB",
      tracking: "N/A",
      controllers: "Temple touchpad + voice",
      waterResistance: "None",
      lenses: "Prescription compatible (Smith Optics frame)",
      features: ["Scene description for blind users", "Text reading (OCR)", "Face recognition", "Document scanning", "Video calling with sighted help", "GPT-4 powered descriptions"],
    },
  },
  {
    id: 62,
    name: "Moverio BT-40S",
    brand: "Epson",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 999,
    releaseYear: 2021,
    image: "👓",
    summary: "Epson's tethered AR glasses with Si-OLED display and a dedicated Android controller unit.",
    specs: {
      display: "Si-OLED, 1920×1080 per eye",
      fov: "34° diagonal",
      camera: "5 MP (on controller)",
      video: "1080p capture",
      audio: "Earphone jack (no built-in speaker)",
      battery: "~6 hours (controller)",
      charging: "USB-C",
      weight: "95g (headset) + 170g (controller)",
      connectivity: "USB-C tether, Wi-Fi 5, Bluetooth 5.0",
      processor: "Qualcomm XR1 (controller)",
      assistant: "None",
      os: "Android 9 (Moverio OS)",
      storage: "64 GB (controller)",
      tracking: "3DoF (head tracking)",
      controllers: "Dedicated HDMI/Android controller",
      waterResistance: "None",
      lenses: "Prescription inserts",
      features: ["Si-OLED see-through display", "Dedicated Android controller", "HDMI input for drones/cameras", "Enterprise SDK", "Wide device compatibility", "Transparent mode"],
    },
  },
  {
    id: 63,
    name: "AirGo Vision",
    brand: "Solos",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 399,
    releaseYear: 2025,
    image: "🕶️",
    summary: "Solos' upgraded AI glasses with camera, micro-AMOLED display, and GPT-4o multimodal AI.",
    specs: {
      display: "Micro-AMOLED waveguide, color",
      fov: "~15° diagonal",
      camera: "8 MP",
      video: "1080p video",
      audio: "Open-ear speakers + dual mic",
      battery: "~5 hours",
      charging: "Magnetic charging",
      weight: "45g",
      connectivity: "Bluetooth 5.3, Wi-Fi",
      processor: "Qualcomm AR SoC",
      assistant: "SolosChat (GPT-4o multimodal)",
      os: "Solos app (iOS/Android)",
      storage: "32 GB",
      tracking: "N/A",
      controllers: "Temple touch controls",
      waterResistance: "IPX4",
      lenses: "Modular front frames, prescription compatible",
      features: ["GPT-4o multimodal AI", "Color AMOLED display", "8 MP camera", "Modular frame design", "Real-time translation", "Visual AI queries"],
    },
  },
  {
    id: 64,
    name: "North Focals",
    brand: "North (Google)",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 599,
    priceNote: "Discontinued (acquired by Google)",
    releaseYear: 2019,
    image: "🕶️",
    summary: "Pioneering smart glasses with a holographic retinal display — discontinued after Google acquisition.",
    specs: {
      display: "Holographic retinal projection",
      fov: "~15° diagonal",
      camera: "None",
      video: "N/A",
      audio: "Bone conduction speaker + mic",
      battery: "~18 hours standby, ~4 hours active",
      charging: "Custom charging loop",
      weight: "40g",
      connectivity: "Bluetooth 4.2",
      processor: "Intel Curie",
      assistant: "Amazon Alexa",
      os: "Focals app (iOS/Android)",
      storage: "N/A",
      tracking: "Loop ring controller",
      controllers: "Focals Loop ring",
      waterResistance: "None",
      lenses: "Custom-fitted prescription",
      features: ["Holographic retinal display", "Alexa integration", "Turn-by-turn navigation", "Notification HUD", "Custom-fitted frames", "Ring controller"],
    },
  },
  {
    id: 65,
    name: "GlassUp Uno",
    brand: "GlassUp",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 399,
    priceNote: "Kickstarter (limited availability)",
    releaseYear: 2023,
    image: "🕶️",
    summary: "Kickstarter-funded Italian smart glasses with monochrome display and notification HUD.",
    specs: {
      display: "Monochrome OLED projected",
      fov: "~12° diagonal",
      camera: "None",
      video: "N/A",
      audio: "Bone conduction + mic",
      battery: "~8 hours",
      charging: "USB-C",
      weight: "42g",
      connectivity: "Bluetooth 5.0",
      processor: "ARM Cortex-M4",
      assistant: "None (notification relay)",
      os: "GlassUp app (iOS/Android)",
      storage: "N/A",
      tracking: "N/A",
      controllers: "Temple touch",
      waterResistance: "IPX3",
      lenses: "Prescription compatible",
      features: ["Notification display", "Calendar alerts", "Turn-by-turn navigation", "Fitness data", "Italian design", "Kickstarter funded"],
    },
  },
  {
    id: 66,
    name: "Vue Smart Glasses",
    brand: "Vue",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 299,
    priceNote: "Kickstarter / Indiegogo",
    releaseYear: 2022,
    image: "🕶️",
    summary: "Crowdfunded audio smart glasses with bone conduction, activity tracking, and voice assistant.",
    specs: {
      display: "No display",
      camera: "None",
      video: "N/A",
      audio: "Bone conduction speakers + mic",
      battery: "~4 hours music",
      charging: "USB-C",
      weight: "38g",
      connectivity: "Bluetooth 5.0",
      processor: "Qualcomm audio SoC",
      assistant: "Siri / Google Assistant (phone relay)",
      os: "Vue app (iOS/Android)",
      storage: "N/A",
      tracking: "Activity tracking (steps, calories)",
      controllers: "Temple touch gestures",
      waterResistance: "IPX4",
      lenses: "Prescription compatible, multiple styles",
      features: ["Bone conduction audio", "Activity & fitness tracking", "Voice assistant relay", "Gesture controls", "Multiple frame styles", "Crowdfunded project"],
    },
  },
  {
    id: 67,
    name: "Oppo Air Glass 3",
    brand: "Oppo",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: null,
    priceNote: "Announced 2024 (limited markets)",
    releaseYear: 2024,
    image: "🕶️",
    summary: "Oppo's AI-first smart glasses with AndesGPT, ultra-slim design, and a subtle waveguide display.",
    specs: {
      display: "Monochrome waveguide, green",
      fov: "~15° diagonal",
      camera: "None",
      video: "N/A",
      audio: "Open-ear speakers + dual mic",
      battery: "~10 hours (estimated)",
      charging: "Magnetic",
      weight: "50g",
      connectivity: "Bluetooth 5.3",
      processor: "Qualcomm AR SoC",
      assistant: "AndesGPT (Oppo AI)",
      os: "Oppo companion app",
      storage: "N/A",
      tracking: "N/A",
      controllers: "Temple touch",
      waterResistance: "IPX4",
      lenses: "Prescription compatible",
      features: ["AndesGPT AI assistant", "Ultra-slim glasses design", "Real-time translation", "Navigation HUD", "Notification display", "Voice-first interaction"],
    },
  },
  {
    id: 68,
    name: "Myvu Discovery",
    brand: "Meizu (Myvu)",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 355,
    releaseYear: 2024,
    image: "🕶️",
    summary: "Meizu's AI smart glasses with Flyme AI, full-color Micro-LED display and retinal-level PPI.",
    specs: {
      display: "Full-color Micro-LED waveguide",
      fov: "~22° diagonal",
      camera: "8 MP",
      video: "Photo + video",
      audio: "Open-ear speakers + dual mic",
      battery: "~7 hours",
      charging: "Magnetic",
      weight: "43g",
      connectivity: "Bluetooth 5.3, Wi-Fi",
      processor: "Qualcomm AR1 Gen 1",
      assistant: "Flyme AI (LLM powered)",
      os: "Myvu companion app",
      storage: "32 GB",
      tracking: "N/A",
      controllers: "Temple touch + voice",
      waterResistance: "IPX4",
      lenses: "Prescription compatible",
      features: ["Full-color Micro-LED display", "Flyme AI assistant", "Real-time translation", "Navigation AR overlay", "Camera for visual AI", "Retinal-level pixel density"],
    },
  },
  {
    id: 69,
    name: "Spectacles 3 (Snap)",
    brand: "Snap Inc.",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 380,
    releaseYear: 2019,
    image: "🕶️",
    summary: "Snap's third-gen camera glasses with dual HD cameras for 3D photo and video capture.",
    specs: {
      display: "No display",
      camera: "Dual HD cameras (3D capture)",
      video: "HD @ 60fps (2D), 3D effects",
      audio: "Dual microphones",
      battery: "~70 snaps per charge",
      charging: "Charging case",
      weight: "56g",
      connectivity: "Bluetooth, Wi-Fi",
      processor: "Snapdragon Wear",
      assistant: "None",
      os: "Snapchat app",
      storage: "4 GB onboard",
      tracking: "N/A",
      controllers: "Button capture",
      waterResistance: "IPX3",
      lenses: "Tinted (sunglasses)",
      features: ["Dual HD cameras", "3D photo capture", "3D effects in Snapchat", "Quick video sharing", "Snap original design", "Portable charging case"],
    },
  },
  {
    id: 70,
    name: "Thunderbird Smart Glasses X2",
    brand: "TCL / Thunderbird",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 329,
    releaseYear: 2024,
    image: "👓",
    summary: "TCL's sub-brand AR glasses with full-color binocular waveguide and AI assistant at a budget price.",
    specs: {
      display: "Full-color Micro-LED waveguide, binocular",
      fov: "~30° diagonal",
      camera: "8 MP",
      video: "1080p video",
      audio: "Open-ear speakers + mic",
      battery: "~4 hours",
      charging: "Magnetic",
      weight: "55g",
      connectivity: "Bluetooth 5.2, Wi-Fi",
      processor: "Qualcomm AR chipset",
      assistant: "AI via app (GPT integration)",
      os: "Thunderbird OS (Android-based)",
      storage: "32 GB",
      tracking: "3DoF",
      controllers: "Temple touch + voice",
      waterResistance: "IPX4",
      lenses: "Prescription inserts",
      features: ["Full-color binocular display", "AI assistant", "Real-time translation", "Navigation overlay", "Photo & video capture", "Budget AR glasses"],
    },
  },
  {
    id: 71,
    name: "Meta Quest 3S",
    brand: "Meta",
    category: "xr",
    categoryLabel: "XR / Mixed Reality",
    price: 299,
    releaseYear: 2024,
    image: "🥽",
    summary: "Meta's most affordable mixed reality headset with color passthrough and full Quest library access.",
    specs: {
      display: "Dual LCD, 1832×1920 per eye",
      fov: "96° horizontal, 90° vertical",
      camera: "Dual 4MP RGB passthrough + depth",
      video: "Mixed reality recording",
      audio: "Integrated stereo speakers, 3.5mm jack",
      battery: "~2.5 hours",
      charging: "USB-C",
      weight: "514g",
      connectivity: "Wi-Fi 6E, Bluetooth 5.3",
      processor: "Snapdragon XR2 Gen 2",
      assistant: "Meta AI",
      os: "Meta Horizon OS",
      storage: "128 GB / 256 GB",
      tracking: "Inside-out 6DoF, hand tracking v2.2",
      controllers: "Touch Plus controllers (included)",
      waterResistance: "None",
      features: ["Most affordable MR headset", "Full Quest game library", "Color passthrough MR", "Hand tracking", "Meta AI integration", "Same chip as Quest 3"],
    },
  },
  {
    id: 72,
    name: "Rokid AR Studio",
    brand: "Rokid",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 799,
    releaseYear: 2025,
    image: "👓",
    summary: "Rokid's premium standalone AR glasses with spatial computing and large-scale AR workspace.",
    specs: {
      display: "Micro-LED waveguide, full color",
      fov: "~45° diagonal",
      camera: "12 MP + depth sensor",
      video: "1080p spatial video",
      audio: "Spatial audio speakers + 3-mic array",
      battery: "~4 hours",
      charging: "USB-C",
      weight: "75g",
      connectivity: "Wi-Fi 6, Bluetooth 5.3",
      processor: "Snapdragon AR2 Gen 1",
      assistant: "Rokid AI",
      os: "YodaOS-XR",
      storage: "128 GB",
      tracking: "6DoF SLAM, hand tracking",
      controllers: "Hand tracking + phone companion",
      waterResistance: "IPX4",
      lenses: "Prescription inserts",
      features: ["Standalone spatial computing", "Large AR workspace", "6DoF spatial tracking", "Hand tracking", "Spatial video capture", "Full-color waveguide"],
    },
  },
  {
    id: 73,
    name: "Bolon Smart Eyewear",
    brand: "Bolon",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 199,
    releaseYear: 2024,
    image: "🕶️",
    summary: "Fashion-forward smart audio glasses from Chinese eyewear giant Bolon with premium styling.",
    specs: {
      display: "No display",
      camera: "None",
      video: "N/A",
      audio: "Open-ear speakers + dual mic",
      battery: "~7 hours music",
      charging: "Magnetic",
      weight: "38g",
      connectivity: "Bluetooth 5.3",
      processor: "Qualcomm audio SoC",
      assistant: "Phone voice assistant relay",
      os: "Companion app",
      storage: "N/A",
      tracking: "N/A",
      controllers: "Temple touch",
      waterResistance: "IPX4",
      lenses: "Prescription compatible, designer frames",
      features: ["Fashion-brand styling", "Premium audio quality", "Open-ear design", "All-day comfort", "Hands-free calling", "Multiple designer frame options"],
    },
  },
  {
    id: 74,
    name: "XRAI Glass",
    brand: "XRAI",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 399,
    priceNote: "Subscription required for AI features",
    releaseYear: 2024,
    image: "🕶️",
    summary: "AI smart glasses focused on real-time captioning for deaf and hard-of-hearing users.",
    specs: {
      display: "Waveguide, monochrome text",
      fov: "~15° diagonal",
      camera: "None",
      video: "N/A",
      audio: "Dual microphones (beamforming)",
      battery: "~8 hours",
      charging: "USB-C",
      weight: "45g",
      connectivity: "Bluetooth 5.2, Wi-Fi",
      processor: "ARM-based SoC",
      assistant: "XRAI AI (captioning + translation)",
      os: "XRAI app (iOS/Android)",
      storage: "N/A",
      tracking: "N/A",
      controllers: "Temple touch",
      waterResistance: "IPX4",
      lenses: "Prescription compatible",
      features: ["Real-time speech captioning", "Live translation (40+ languages)", "Accessibility focused", "Speaker identification", "Conversation transcripts", "Works for deaf/HoH users"],
    },
  },
  {
    id: 75,
    name: "Lenovo Legion Glasses",
    brand: "Lenovo",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: 329,
    releaseYear: 2023,
    image: "👓",
    summary: "Lenovo's gaming-focused display glasses with micro-OLED and plug-and-play USB-C connectivity.",
    specs: {
      display: "Micro-OLED, 1920×1080 per eye",
      fov: "45° diagonal",
      camera: "None",
      video: "N/A",
      audio: "Dual speakers + dual mic",
      battery: "N/A (tethered)",
      charging: "USB-C passthrough",
      weight: "96g",
      connectivity: "USB-C (DP Alt Mode)",
      processor: "Host device",
      assistant: "None",
      os: "Plug-and-play",
      storage: "N/A",
      tracking: "3DoF",
      controllers: "Host device",
      waterResistance: "None",
      lenses: "Diopter adjustment",
      features: ["Gaming-optimized display", "Micro-OLED crisp visuals", "Plug-and-play USB-C", "3DoF head tracking", "Works with Steam Deck/ROG Ally", "Private gaming screen"],
    },
  },
  {
    id: 76,
    name: "Jio Glass",
    brand: "Reliance Jio",
    category: "ar",
    categoryLabel: "AR Glasses",
    price: null,
    priceNote: "India-only, limited availability",
    releaseYear: 2022,
    image: "👓",
    summary: "Reliance Jio's mixed reality glasses designed for holographic video calls and Indian market apps.",
    specs: {
      display: "Dual 1080p holographic display",
      fov: "~45° diagonal",
      camera: "Depth camera",
      video: "Holographic calling",
      audio: "Spatial audio speakers + mic",
      battery: "N/A (tethered to phone)",
      charging: "USB-C",
      weight: "75g",
      connectivity: "USB-C, Bluetooth",
      processor: "Qualcomm XR1",
      assistant: "Jio AI",
      os: "Jio MR OS",
      storage: "N/A (phone-based)",
      tracking: "3DoF",
      controllers: "Phone + hand gestures",
      waterResistance: "None",
      features: ["Holographic video calls", "25+ Jio MR apps", "3D classroom education", "India-focused ecosystem", "Teacher-student AR", "Lightweight design"],
    },
  },
  {
    id: 77,
    name: "Frame by Brilliant Labs (2nd Gen)",
    brand: "Brilliant Labs",
    category: "ai",
    categoryLabel: "AI Glasses",
    price: 399,
    releaseYear: 2025,
    image: "🕶️",
    summary: "Updated open-source AI glasses with improved camera, longer battery, and enhanced Noa AI.",
    specs: {
      display: "Micro-OLED, 640×400, color",
      fov: "~20° diagonal",
      camera: "12 MP (upgraded)",
      video: "Photo + short video",
      audio: "Speaker + dual mic",
      battery: "~6 hours active",
      charging: "USB-C",
      weight: "38g",
      connectivity: "Bluetooth 5.4",
      processor: "Nordic nRF5340 (updated firmware)",
      assistant: "Noa 2.0 (multimodal AI)",
      os: "Open-source (MicroPython / community)",
      storage: "N/A",
      tracking: "Tap gestures",
      controllers: "Tap + voice",
      waterResistance: "IPX4",
      lenses: "Prescription compatible",
      features: ["Open-source platform", "12 MP upgraded camera", "Noa 2.0 multimodal AI", "Real-time visual search", "Improved battery life", "Developer community apps"],
    },
  },
];

